# Generated by Django 5.0.1 on 2024-02-17 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCommodityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='نوع کالا')),
            ],
            options={
                'verbose_name': 'نوع کالا',
                'verbose_name_plural': 'انواع کالا',
            },
        ),
        migrations.CreateModel(
            name='GlobalIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام صنعت')),
            ],
            options={
                'verbose_name': 'صنعت',
                'verbose_name_plural': 'صنایع',
            },
        ),
        migrations.CreateModel(
            name='GlobalTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transit_type', models.CharField(max_length=255, verbose_name='نوع ترانزیت')),
                ('transit_unit', models.CharField(max_length=255, verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'ترانزیت',
                'verbose_name_plural': 'ترانزیت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='GlobalCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='global_market.globalcommoditytype', verbose_name='نوع کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.AddField(
            model_name='globalcommoditytype',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_types', to='global_market.globalindustry', verbose_name='صنعت'),
        ),
        migrations.CreateModel(
            name='GlobalTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateField(verbose_name='تاریخ معامله')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_market.globalcommodity', verbose_name='کالا')),
                ('transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_market.globaltransit', verbose_name='ترانزیت')),
            ],
            options={
                'verbose_name': 'معامله',
                'verbose_name_plural': 'معاملات',
            },
        ),
        migrations.CreateModel(
            name='FavoriteRatioChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ratio_charts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('commodity_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ratio_commodity_1', to='global_market.globalcommodity', verbose_name='کالا ۱')),
                ('commodity_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ratio_commodity_2', to='global_market.globalcommodity', verbose_name='کالا ۲')),
                ('commodity_type_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ratio_commodity_type_1', to='global_market.globalcommoditytype', verbose_name='نوع کالا ۱')),
                ('commodity_type_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ratio_commodity_type_2', to='global_market.globalcommoditytype', verbose_name='نوع کالا ۲')),
                ('industry_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ratio_industry_1', to='global_market.globalindustry', verbose_name='صنعت ۱')),
                ('industry_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ratio_industry_2', to='global_market.globalindustry', verbose_name='صنعت ۲')),
                ('transit_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ratio_transit_1', to='global_market.globaltransit', verbose_name='ترانزیت ۱')),
                ('transit_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ratio_transit_2', to='global_market.globaltransit', verbose_name='ترانزیت ۲')),
            ],
            options={
                'verbose_name': 'نسبت قیمت مورد علاقه',
                'verbose_name_plural': 'نسبت\u200cهای قیمت مورد علاقه',
                'unique_together': {('user', 'industry_1', 'commodity_type_1', 'commodity_1', 'transit_1', 'industry_2', 'commodity_type_2', 'commodity_2', 'transit_2')},
            },
        ),
        migrations.CreateModel(
            name='FavoritePriceChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_price_charts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_market.globalcommodity', verbose_name='کالا')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_market.globalcommoditytype', verbose_name='نوع کالا')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_market.globalindustry', verbose_name='صنعت')),
                ('transit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_market.globaltransit', verbose_name='ترانزیت')),
            ],
            options={
                'verbose_name': 'نمودار قیمت مورد علاقه',
                'verbose_name_plural': 'نمودارهای قیمت مورد علاقه',
                'unique_together': {('user', 'industry', 'commodity_type', 'commodity', 'transit')},
            },
        ),
    ]
