# Generated by Django 5.0.1 on 2024-03-04 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteratiochart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoriteratiochart',
            name='commodity_1',
        ),
        migrations.RemoveField(
            model_name='favoriteratiochart',
            name='commodity_2',
        ),
        migrations.RemoveField(
            model_name='favoriteratiochart',
            name='commodity_type_1',
        ),
        migrations.RemoveField(
            model_name='favoriteratiochart',
            name='commodity_type_2',
        ),
        migrations.RemoveField(
            model_name='favoriteratiochart',
            name='industry_1',
        ),
        migrations.RemoveField(
            model_name='favoriteratiochart',
            name='industry_2',
        ),
        migrations.RemoveField(
            model_name='favoriteratiochart',
            name='transit_1',
        ),
        migrations.RemoveField(
            model_name='favoriteratiochart',
            name='transit_2',
        ),
        migrations.RemoveField(
            model_name='favoriteratiochart',
            name='user',
        ),
        migrations.CreateModel(
            name='GlobalFavoritePriceChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_market.globalcommodity', verbose_name='کالا')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_market.globalcommoditytype', verbose_name='نوع کالا')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_market.globalindustry', verbose_name='صنعت')),
                ('transit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global_market.globaltransit', verbose_name='ترانزیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_favorite_price_charts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نمودار قیمت مورد علاقه',
                'verbose_name_plural': 'نمودارهای قیمت مورد علاقه',
                'unique_together': {('user', 'industry', 'commodity_type', 'commodity', 'transit')},
            },
        ),
        migrations.CreateModel(
            name='GlobalFavoriteRatioChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_favorite_ratio_commodity_1', to='global_market.globalcommodity', verbose_name='کالا ۱')),
                ('commodity_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_favorite_ratio_commodity_2', to='global_market.globalcommodity', verbose_name='کالا ۲')),
                ('commodity_type_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_favorite_ratio_commodity_type_1', to='global_market.globalcommoditytype', verbose_name='نوع کالا ۱')),
                ('commodity_type_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_favorite_ratio_commodity_type_2', to='global_market.globalcommoditytype', verbose_name='نوع کالا ۲')),
                ('industry_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_favorite_ratio_industry_1', to='global_market.globalindustry', verbose_name='صنعت ۱')),
                ('industry_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_favorite_ratio_industry_2', to='global_market.globalindustry', verbose_name='صنعت ۲')),
                ('transit_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_favorite_ratio_transit_1', to='global_market.globaltransit', verbose_name='ترانزیت ۱')),
                ('transit_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_favorite_ratio_transit_2', to='global_market.globaltransit', verbose_name='ترانزیت ۲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_favorite_ratio_charts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نسبت قیمت مورد علاقه',
                'verbose_name_plural': 'نسبت\u200cهای قیمت مورد علاقه',
                'unique_together': {('user', 'industry_1', 'commodity_type_1', 'commodity_1', 'transit_1', 'industry_2', 'commodity_type_2', 'commodity_2', 'transit_2')},
            },
        ),
        migrations.DeleteModel(
            name='FavoritePriceChart',
        ),
        migrations.DeleteModel(
            name='FavoriteRatioChart',
        ),
    ]
