# Generated by Django 5.0.1 on 2024-04-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_market', '0002_alter_favoriteratiochart_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='globalfavoriteratiochart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='globalfavoriteratiochart',
            name='commodity_1',
        ),
        migrations.RemoveField(
            model_name='globalfavoriteratiochart',
            name='commodity_2',
        ),
        migrations.RemoveField(
            model_name='globalfavoriteratiochart',
            name='commodity_type_1',
        ),
        migrations.RemoveField(
            model_name='globalfavoriteratiochart',
            name='commodity_type_2',
        ),
        migrations.RemoveField(
            model_name='globalfavoriteratiochart',
            name='industry_1',
        ),
        migrations.RemoveField(
            model_name='globalfavoriteratiochart',
            name='industry_2',
        ),
        migrations.RemoveField(
            model_name='globalfavoriteratiochart',
            name='transit_1',
        ),
        migrations.RemoveField(
            model_name='globalfavoriteratiochart',
            name='transit_2',
        ),
        migrations.RemoveField(
            model_name='globalfavoriteratiochart',
            name='user',
        ),
        migrations.DeleteModel(
            name='GlobalFavoritePriceChart',
        ),
        migrations.DeleteModel(
            name='GlobalFavoriteRatioChart',
        ),
    ]
