# Generated by Django 5.0.1 on 2024-04-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_market', '0003_alter_globalfavoriteratiochart_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalcommodity',
            options={'verbose_name': 'کالا', 'verbose_name_plural': '3: کالاها'},
        ),
        migrations.AlterModelOptions(
            name='globalcommoditytype',
            options={'verbose_name': 'نوع کالا', 'verbose_name_plural': '2: انواع کالا'},
        ),
        migrations.AlterModelOptions(
            name='globalindustry',
            options={'verbose_name': 'صنعت', 'verbose_name_plural': '1: صنایع'},
        ),
        migrations.AlterModelOptions(
            name='globaltrade',
            options={'verbose_name': 'معامله', 'verbose_name_plural': '5: معاملات'},
        ),
        migrations.AlterModelOptions(
            name='globaltransit',
            options={'verbose_name': 'ترانزیت', 'verbose_name_plural': '4: ترانزیت\u200cها'},
        ),
    ]
