# Generated by Django 5.0.1 on 2024-05-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_market', '0004_alter_globalcommodity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalcommodity',
            options={'verbose_name': 'کالا', 'verbose_name_plural': '۳) کالاها'},
        ),
        migrations.AlterModelOptions(
            name='globalcommoditytype',
            options={'verbose_name': 'نوع کالا', 'verbose_name_plural': '۲) انواع کالا'},
        ),
        migrations.AlterModelOptions(
            name='globalindustry',
            options={'verbose_name': 'صنعت', 'verbose_name_plural': '۱) صنایع'},
        ),
        migrations.AlterModelOptions(
            name='globaltrade',
            options={'verbose_name': 'معامله', 'verbose_name_plural': '۵) معاملات'},
        ),
        migrations.AlterModelOptions(
            name='globaltransit',
            options={'verbose_name': 'ترانزیت', 'verbose_name_plural': '۴) ترانزیت\u200cها'},
        ),
    ]
