# Generated by Django 5.0.1 on 2024-05-29 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_market', '0005_alter_globalcommodity_options_and_more'),
        ('stock_market', '0019_rename_stockmonthlyactivityreport_codalmonthlyactivityreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('global_commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='global_market.globalcommoditytype', verbose_name='نوع کالا')),
                ('stock_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='stock_market.stockinstrument', verbose_name='سهم')),
            ],
            options={
                'verbose_name': 'ارتباط',
                'verbose_name_plural': '۵) ارتباط\u200cها',
                'unique_together': {('global_commodity_type', 'stock_instrument')},
            },
        ),
    ]
