# Generated by Django 5.0.1 on 2024-05-29 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_market', '0006_globalrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalrelation',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': '۶) ارتباط\u200cها'},
        ),
    ]
