# Generated by Django 5.0.1 on 2024-08-05 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_market', '0007_alter_globalrelation_options'),
        ('stock_market', '0042_alter_buypressure_ascending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalrelation',
            name='stock_instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_relations', to='stock_market.stockinstrument', verbose_name='سهم'),
        ),
    ]
