# Generated by Django 5.0.1 on 2025-01-22 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reg_no', models.CharField(max_length=16, verbose_name='شماره ثبت')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
                ('invest_type', models.CharField(default='نامشخص', max_length=32, verbose_name='نوع سرمایه\u200cگذاری')),
                ('initiation_date', models.DateField(verbose_name='شروع')),
                ('dividend_interval_period', models.IntegerField(default=0, verbose_name='دوره تقسیم سود')),
                ('guaranteed_earning_rate', models.IntegerField(default=0, verbose_name='بازدهی تضمین شده')),
                ('last_date', models.DateField(verbose_name='آخرین به\u200cروزرسانی')),
                ('fund_manager', models.CharField(default='نامشخص', max_length=64, verbose_name='مدیر سرمایه\u200cگذاری')),
                ('market_maker', models.CharField(default='نامشخص', max_length=64, verbose_name='بازارساز')),
                ('website', models.CharField(default='نامشخص', max_length=64, verbose_name='وبسایت')),
                ('guarantor', models.CharField(default='نامشخص', max_length=64, verbose_name='تضمین کننده')),
                ('investment_manager', models.CharField(default='نامشخص', max_length=64, verbose_name='مدیران سرمایه\u200cگذاری')),
                ('national_id', models.CharField(default='نامشخص', max_length=64, verbose_name='شناسه ملی')),
                ('ins_code', models.CharField(default='نامشخص', max_length=64, verbose_name='شناسه بورسی')),
                ('fund_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='fund.fundtype')),
            ],
            options={
                'verbose_name': 'اطلاعات کلی صندوق',
                'verbose_name_plural': '۲) اطلاعات کلی صندوق\u200cها',
            },
        ),
    ]
