# Generated by Django 5.0.1 on 2025-01-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_fundinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinfo',
            name='fund_manager',
            field=models.CharField(default='نامشخص', max_length=128, verbose_name='مدیر سرمایه\u200cگذاری'),
        ),
        migrations.AlterField(
            model_name='fundinfo',
            name='guarantor',
            field=models.CharField(default='نامشخص', max_length=128, verbose_name='تضمین کننده'),
        ),
        migrations.AlterField(
            model_name='fundinfo',
            name='investment_manager',
            field=models.CharField(default='نامشخص', max_length=128, verbose_name='مدیران سرمایه\u200cگذاری'),
        ),
        migrations.AlterField(
            model_name='fundinfo',
            name='market_maker',
            field=models.CharField(default='نامشخص', max_length=128, verbose_name='بازارساز'),
        ),
        migrations.AlterField(
            model_name='fundinfo',
            name='name',
            field=models.CharField(max_length=128, verbose_name='نام'),
        ),
    ]
