# Generated by Django 5.0.1 on 2025-01-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_alter_fundinfo_fund_manager_alter_fundinfo_guarantor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_nav', models.IntegerField(verbose_name='ابطال')),
                ('issue_nav', models.IntegerField(verbose_name='صدور')),
                ('statistical_nav', models.IntegerField(verbose_name='آماری')),
                ('fund_size', models.BigIntegerField(verbose_name='اندازه')),
                ('net_asset', models.BigIntegerField(verbose_name='اندازه')),
                ('weekly', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='روزانه')),
                ('monthly', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ماهانه')),
                ('quarterly', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='سه ماهه')),
                ('six_month', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='شش ماهه')),
                ('annual', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='سالانه')),
                ('fund_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funds', to='fund.fundinfo')),
            ],
            options={
                'verbose_name': 'اطلاعات مالی صندوق\u200c',
                'verbose_name_plural': '۳) اطلاعات مالی صندوق\u200cها',
            },
        ),
    ]
