# Generated by Django 5.0.1 on 2025-01-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_fundfinance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundfinance',
            name='daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='روزانه'),
        ),
        migrations.AlterField(
            model_name='fundfinance',
            name='weekly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='هفتگی'),
        ),
    ]
