# Generated by Django 5.0.1 on 2025-01-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_fundfinance_daily_alter_fundfinance_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundfinance',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='سالانه'),
        ),
    ]
