# Generated by Django 5.0.1 on 2025-01-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0006_fundfinance_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FundFinance',
        ),
    ]
