# Generated by Django 5.0.1 on 2025-01-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0007_delete_fundfinance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundinfo',
            name='investment_manager',
        ),
        migrations.RemoveField(
            model_name='fundinfo',
            name='market_maker',
        ),
        migrations.RemoveField(
            model_name='fundinfo',
            name='national_id',
        ),
    ]
