# Generated by Django 5.0.1 on 2024-10-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': '۱) پروفایل\u200cها'},
        ),
    ]
