# Generated by Django 5.0.1 on 2024-10-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_login',
            field=models.IntegerField(default=1, verbose_name='حداکثر لاگین همزمان'),
        ),
    ]
