# Generated by Django 5.0.1 on 2024-10-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('all_feature', 'تمام قابلیت\u200cها')], max_length=32, verbose_name='قابلیت سایت')),
                ('duration', models.IntegerField(choices=[(1, '۱ ماه'), (3, '۳ ماه'), (6, '۶ ماه'), (12, '۱۲ ماه')], verbose_name='مدت زمان')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('has_discount', models.BooleanField(default=False, verbose_name='تخفیف')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='میزان تخفیف')),
            ],
            options={
                'verbose_name': 'قابلیت سایت',
                'verbose_name_plural': '۲) قابلیت\u200cهای سایت',
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اشتراک', 'verbose_name_plural': '۳) اشتراک\u200cها'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='account.feature', verbose_name='قابلیت سایت'),
        ),
    ]
