# Generated by Django 5.0.1 on 2024-10-27 08:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_feature_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=255, verbose_name='نام تخفیف')),
                ('description', models.TextField(default='', verbose_name='توضیحات تخفیف')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='میزان تخفیف')),
                ('has_discount_code', models.BooleanField(default=False, verbose_name='کد تخفیف دارد؟')),
                ('discount_code', models.CharField(default='', verbose_name='کد تخفیف')),
                ('has_start', models.BooleanField(default=False, verbose_name='تاریخ شروع دارد؟')),
                ('start_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان شروع')),
                ('has_expiry', models.BooleanField(default=False, verbose_name='تاریخ پایان دارد؟')),
                ('expire_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان پایان')),
                ('has_max_use_count', models.BooleanField(default=False, verbose_name='محدودیت دفعات استفاده')),
                ('used_count', models.IntegerField(default=0, verbose_name='دفعات استفاده شده')),
                ('max_use_count', models.IntegerField(default=1000, verbose_name='محدودیت دفعات استفاده')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='account.feature', verbose_name='قابلیت سایت')),
            ],
            options={
                'verbose_name': 'تخفیف قابلیت سایت',
                'verbose_name_plural': '۴) تخفیف\u200cهای قابلیت\u200cهای سایت',
            },
        ),
    ]
