# Generated by Django 5.0.1 on 2024-10-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_featurediscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurediscount',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات تخفیف'),
        ),
        migrations.AlterField(
            model_name='featurediscount',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='نام تخفیف'),
        ),
    ]
