# Generated by Django 5.0.1 on 2024-10-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_featurediscount_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurediscount',
            name='discount_code',
            field=models.CharField(blank=True, default='', verbose_name='کد تخفیف'),
        ),
    ]
