# Generated by Django 5.0.1 on 2024-10-27 09:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_featurediscount_discount_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='نام تخفیف')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات تخفیف')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='میزان تخفیف')),
                ('has_discount_code', models.BooleanField(default=False, verbose_name='کد تخفیف دارد؟')),
                ('discount_code', models.CharField(blank=True, default='', verbose_name='کد تخفیف')),
                ('has_start', models.BooleanField(default=False, verbose_name='تاریخ شروع دارد؟')),
                ('start_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان شروع')),
                ('has_expiry', models.BooleanField(default=False, verbose_name='تاریخ پایان دارد؟')),
                ('expire_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='زمان پایان')),
                ('has_max_use_count', models.BooleanField(default=False, verbose_name='محدودیت دفعات استفاده')),
                ('used_count', models.IntegerField(default=0, verbose_name='دفعات استفاده شده')),
                ('max_use_count', models.IntegerField(default=1000, verbose_name='محدودیت دفعات استفاده')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discounts', to='account.feature', verbose_name='قابلیت سایت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تخفیف کاربر',
                'verbose_name_plural': '۵) تخفیف\u200cهای کاربران',
            },
        ),
    ]
