# Generated by Django 5.0.1 on 2024-10-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_login',
            field=models.IntegerField(default=0, verbose_name='لاگین\u200cهای همزمان'),
        ),
    ]
