# Generated by Django 5.0.1 on 2024-12-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_active_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='login_count',
            field=models.IntegerField(default=1, verbose_name='تعداد کاربران'),
        ),
    ]
