# Generated by Django 5.0.1 on 2024-12-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_feature_login_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscount',
            name='max_use_count',
            field=models.IntegerField(default=1, verbose_name='محدودیت دفعات استفاده'),
        ),
    ]
