# Generated by Django 5.0.1 on 2024-12-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_userdiscount_max_use_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(choices=[('all_feature', 'تمام قابلیت\u200cهای سایت')], max_length=32, verbose_name='قابلیت سایت'),
        ),
    ]
