# Generated by Django 5.0.1 on 2024-12-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_feature_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurediscount',
            options={'verbose_name': 'تخفیف قابلیت سایت', 'verbose_name_plural': '۳) تخفیف\u200cهای قابلیت\u200cهای سایت'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اشتراک', 'verbose_name_plural': '۵) اشتراک\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='userdiscount',
            options={'verbose_name': 'تخفیف کاربر', 'verbose_name_plural': '۴) تخفیف\u200cهای کاربران'},
        ),
    ]
