# Generated by Django 5.0.1 on 2024-12-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_featurediscount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
