# Generated by Django 5.0.1 on 2024-12-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_feature_is_enabled_subscription_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.CharField(default='-', max_length=32, verbose_name='توضیحات'),
        ),
    ]
