# Generated by Django 5.0.1 on 2024-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_profile_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(choices=[('all_feature', 'تمام قابلیت\u200cهای سایت'), ('option_feature', 'بخش آپشن\u200cها')], max_length=32, verbose_name='قابلیت سایت'),
        ),
    ]
