# Generated by Django 5.0.1 on 2024-12-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_feature_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(choices=[('all_feature', 'تمام قابلیت\u200cهای سایت'), ('domestic_feature', 'بخش بورس کالای داخلی'), ('future_feature', 'بخش ابزارهای مشتقه بورس کالا'), ('global_feature', 'بخش بازارهای جهانی'), ('option_feature', 'بخش آپشن\u200cها')], max_length=32, verbose_name='قابلیت سایت'),
        ),
    ]
