# Generated by Django 5.0.1 on 2025-01-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_subscription_desc_alter_feature_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledFeature',
            fields=[
            ],
            options={
                'verbose_name': 'قابلیت سایت (غیرفعال)',
                'verbose_name_plural': '۲) قابلیت\u200cهای سایت (غیرفعال)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.feature',),
        ),
    ]
