# Generated by Django 5.0.1 on 2025-01-15 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_disabledfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledFeatureDiscount',
            fields=[
            ],
            options={
                'verbose_name': 'تخفیف قابلیت سایت (غیرفعال)',
                'verbose_name_plural': '۳) تخفیف\u200cهای قابلیت\u200cهای سایت (غیرفعال)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.featurediscount',),
        ),
    ]
