# Generated by Django 5.0.1 on 2025-01-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_disabledfeaturediscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledSubscription',
            fields=[
            ],
            options={
                'verbose_name': 'اشتراک (غیرفعال)',
                'verbose_name_plural': '۵) اشتراک\u200cها (غیرفعال)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.subscription',),
        ),
        migrations.CreateModel(
            name='DisabledUserDiscount',
            fields=[
            ],
            options={
                'verbose_name': 'تخفیف کاربر (غیرفعال)',
                'verbose_name_plural': '۴) تخفیف\u200cهای کاربران (غیرفعال)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.userdiscount',),
        ),
    ]
