# Generated by Django 5.0.1 on 2025-01-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_disabledsubscription_disableduserdiscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'قابلیت سایت (فعال)', 'verbose_name_plural': '۲)  (فعال) قابلیت\u200cهای سایت'},
        ),
        migrations.AlterModelOptions(
            name='featurediscount',
            options={'verbose_name': ' (فعال) تخفیف قابلیت سایت', 'verbose_name_plural': '۳) (فعال) تخفیف\u200cهای قابلیت\u200cهای سایت'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': '(فعال) اشتراک', 'verbose_name_plural': '۵) (فعال) اشتراک\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='userdiscount',
            options={'verbose_name': '(فعال) تخفیف کاربر', 'verbose_name_plural': '۴) (فعال) تخفیف\u200cهای کاربران'},
        ),
    ]
