# Generated by Django 5.0.1 on 2025-04-13 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_feature_options_alter_featurediscount_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=1, verbose_name='تعداد لاگین')),
                ('note', models.CharField(default='-', max_length=32, verbose_name='توضیحات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logincount', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تعداد لاگین',
                'verbose_name_plural': '۶) تعداد لاگین\u200cها',
            },
        ),
    ]
