# Generated by Django 5.0.1 on 2025-11-08 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_logincount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_logged_in', models.BooleanField(default=False, verbose_name='لاگین\u200cاول؟')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='first_login', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگین اول',
                'verbose_name_plural': '۷) لاگین\u200cهای اول',
            },
        ),
    ]
