# Generated by Django 5.0.1 on 2024-04-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=255, verbose_name='نماد')),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('codal_id', models.CharField(max_length=255, verbose_name='آیدی کدال')),
                ('codal_t', models.IntegerField(verbose_name='فیلد t')),
                ('codal_st', models.IntegerField(verbose_name='فیلد st')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': '1: شرکت\u200cها',
            },
        ),
    ]
