# Generated by Django 5.0.1 on 2024-04-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcompany',
            name='codal_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='آیدی کدال'),
        ),
    ]
