# Generated by Django 5.0.1 on 2024-04-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0003_alter_stockcompany_codal_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMonthlyActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracing_number', models.IntegerField(verbose_name='کد رهگیری')),
                ('under_supervision', models.IntegerField(verbose_name='تحت نظارت')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('code', models.CharField(max_length=255, verbose_name='عنوان')),
                ('sent_date_time', models.DateTimeField(verbose_name='زمان ارسال')),
                ('publish_date_time', models.DateTimeField(verbose_name='زمان انتشار')),
                ('has_html', models.BooleanField(verbose_name='اچ\u200cتی\u200cام\u200cال')),
                ('is_estimate', models.BooleanField(verbose_name='تقریبی')),
                ('url', models.CharField(max_length=255, verbose_name='آدرس')),
                ('has_excel', models.BooleanField(verbose_name='اکسل')),
                ('has_pdf', models.BooleanField(verbose_name='پی\u200cدی\u200cاف')),
                ('has_xbrl', models.BooleanField(verbose_name='ایکس بی آر ال')),
                ('has_attachment', models.BooleanField(verbose_name='پیوست')),
                ('attachment_url', models.CharField(max_length=255, verbose_name='آدرس پیوست')),
                ('pdf_url', models.CharField(max_length=255, verbose_name='آدرس پی\u200cدی\u200cاف')),
                ('excel_url', models.CharField(max_length=255, verbose_name='آدرس اکسل')),
                ('xbrl_url', models.CharField(max_length=255, verbose_name='آدرس ایکس\u200cبی\u200cآرال')),
                ('supervision', models.TextField(verbose_name='نظارت')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_monthly_activity', to='stock_market.stockcompany')),
            ],
            options={
                'verbose_name': 'گزارش\u200c فعالیت ماهانه',
                'verbose_name_plural': '1: گزارش\u200cهای فعالیت\u200c ماهانه',
            },
        ),
    ]
