# Generated by Django 5.0.1 on 2024-04-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0004_stockmonthlyactivityreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmonthlyactivityreport',
            name='code',
            field=models.CharField(max_length=255, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='stockmonthlyactivityreport',
            name='tracing_number',
            field=models.IntegerField(unique=True, verbose_name='کد رهگیری'),
        ),
    ]
