# Generated by Django 5.0.1 on 2024-05-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0005_alter_stockmonthlyactivityreport_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=255, unique=True, verbose_name='نماد')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('ins_code', models.CharField(max_length=255, verbose_name='کد سهم')),
            ],
            options={
                'verbose_name': 'سهم',
                'verbose_name_plural': '1: سهم\u200cها',
            },
        ),
        migrations.AlterModelOptions(
            name='stockcompany',
            options={'verbose_name': 'شرکت', 'verbose_name_plural': '2: شرکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='stockmonthlyactivityreport',
            options={'verbose_name': 'گزارش\u200c فعالیت ماهانه', 'verbose_name_plural': '3: گزارش\u200cهای فعالیت\u200c ماهانه'},
        ),
    ]
