# Generated by Django 5.0.1 on 2024-05-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0006_stocksymbol_alter_stockcompany_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksymbol',
            name='ins_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='کد سهم'),
        ),
    ]
