# Generated by Django 5.0.1 on 2024-05-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0007_alter_stocksymbol_ins_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockcompany',
            options={'verbose_name': 'شرکت', 'verbose_name_plural': '۲) شرکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='stockmonthlyactivityreport',
            options={'verbose_name': 'گزارش\u200c فعالیت ماهانه', 'verbose_name_plural': '۳) گزارش\u200cهای فعالیت\u200c ماهانه'},
        ),
        migrations.AlterModelOptions(
            name='stocksymbol',
            options={'verbose_name': 'سهم', 'verbose_name_plural': '۱) سهم\u200cها'},
        ),
    ]
