# Generated by Django 5.0.1 on 2024-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0008_alter_stockcompany_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIndustrialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(unique=True, verbose_name='کد صنعت')),
                ('name', models.CharField(max_length=255, verbose_name='نام صنعت')),
            ],
            options={
                'verbose_name': 'صنعت',
                'verbose_name_plural': '۱) صنایع',
            },
        ),
        migrations.DeleteModel(
            name='StockSymbol',
        ),
        migrations.AlterModelOptions(
            name='stockcompany',
            options={'verbose_name': 'شرکت', 'verbose_name_plural': 'شرکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='stockmonthlyactivityreport',
            options={'verbose_name': 'گزارش\u200c فعالیت ماهانه', 'verbose_name_plural': 'گزارش\u200cهای فعالیت\u200c ماهانه'},
        ),
    ]
