# Generated by Django 5.0.1 on 2024-05-12 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0009_stockindustrialgroup_delete_stocksymbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_type', models.IntegerField(choices=[(1, 'بورس'), (2, 'فرابورس')], verbose_name='نوع بازار')),
                ('paper_type', models.IntegerField(choices=[(1, 'بورس'), (2, 'فرابورس')], verbose_name='نوع اوراق')),
                ('ins_code', models.CharField(max_length=255, unique=True, verbose_name='کد نماد')),
                ('ins_id', models.CharField(max_length=255, unique=True, verbose_name='شناسه نماد')),
                ('symbol', models.CharField(max_length=255, verbose_name='نماد')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('industrial_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='stock_market.stockindustrialgroup')),
            ],
            options={
                'verbose_name': 'نماد',
                'verbose_name_plural': '۲) نمادها',
            },
        ),
    ]
