# Generated by Django 5.0.1 on 2024-05-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0010_stockinstrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinstrument',
            name='paper_type',
            field=models.IntegerField(choices=[(1, 'سهام'), (2, 'بازار پایه فرابورس'), (3, 'تسهیلات مسکن'), (4, 'حق تقدم'), (5, 'اوراق بدهی'), (6, 'اختیار معامله'), (7, 'آتی'), (8, 'صندوق\u200cهای سرمایه\u200cگذاری'), (9, 'بورس کالا')], verbose_name='نوع اوراق'),
        ),
    ]
