# Generated by Django 5.0.1 on 2024-05-13 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0011_alter_stockinstrument_paper_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInstrumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateField(verbose_name='تاریخ')),
                ('trade_count', models.IntegerField(verbose_name='تعداد معاملات')),
                ('volume', models.IntegerField(verbose_name='حجم معاملات')),
                ('value', models.BigIntegerField(verbose_name='ارزش معاملات')),
                ('yesterday_price', models.IntegerField(verbose_name='قیمت دیروز')),
                ('open', models.IntegerField(verbose_name='اولین قیمت')),
                ('close', models.IntegerField(verbose_name='آخرین قیمت')),
                ('low', models.IntegerField(verbose_name='کمترین قیمت')),
                ('high', models.IntegerField(verbose_name='بیشترین قیمت')),
                ('close_mean', models.IntegerField(verbose_name='قیمت پایانی')),
                ('individual_buy_count', models.IntegerField(verbose_name='تعداد خرید حقیقی')),
                ('individual_buy_volume', models.IntegerField(verbose_name='حجم خرید حقیقی')),
                ('individual_buy_value', models.BigIntegerField(verbose_name='ارزش خرید حقیقی')),
                ('legal_buy_count', models.IntegerField(verbose_name='تعداد خرید حقوقی')),
                ('legal_buy_volume', models.IntegerField(verbose_name='حجم خرید حقوقی')),
                ('legal_buy_value', models.BigIntegerField(verbose_name='ارزش خرید حقوقی')),
                ('individual_sell_count', models.IntegerField(verbose_name='تعداد فروش حقیقی')),
                ('individual_sell_volume', models.IntegerField(verbose_name='حجم فروش حقیقی')),
                ('individual_sell_value', models.BigIntegerField(verbose_name='ارزش فروش حقیقی')),
                ('legal_sell_count', models.IntegerField(verbose_name='تعداد فروش حقوقی')),
                ('legal_sell_volume', models.IntegerField(verbose_name='حجم فروش حقوقی')),
                ('legal_sell_value', models.BigIntegerField(verbose_name='ارزش فروش حقوقی')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='stock_market.stockinstrument', verbose_name='نماد')),
            ],
            options={
                'verbose_name': 'تاریخچه',
                'verbose_name_plural': '۳) تاریخچه\u200cها',
            },
        ),
    ]
