# Generated by Django 5.0.1 on 2024-05-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0012_stockinstrumenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinstrumenthistory',
            name='individual_buy_volume',
            field=models.BigIntegerField(verbose_name='حجم خرید حقیقی'),
        ),
        migrations.AlterField(
            model_name='stockinstrumenthistory',
            name='individual_sell_volume',
            field=models.BigIntegerField(verbose_name='حجم فروش حقیقی'),
        ),
        migrations.AlterField(
            model_name='stockinstrumenthistory',
            name='legal_buy_volume',
            field=models.BigIntegerField(verbose_name='حجم خرید حقوقی'),
        ),
        migrations.AlterField(
            model_name='stockinstrumenthistory',
            name='legal_sell_volume',
            field=models.BigIntegerField(verbose_name='حجم فروش حقوقی'),
        ),
        migrations.AlterField(
            model_name='stockinstrumenthistory',
            name='volume',
            field=models.BigIntegerField(verbose_name='حجم معاملات'),
        ),
        migrations.AlterUniqueTogether(
            name='stockinstrumenthistory',
            unique_together={('instrument', 'trade_date')},
        ),
    ]
