# Generated by Django 5.0.1 on 2024-05-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0013_alter_stockinstrumenthistory_individual_buy_volume_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockindustrialgroup',
            options={'verbose_name': 'صنعت', 'verbose_name_plural': '۱۱) صنایع'},
        ),
        migrations.AlterModelOptions(
            name='stockinstrument',
            options={'verbose_name': 'نماد', 'verbose_name_plural': '۱۲) نمادها'},
        ),
        migrations.AlterModelOptions(
            name='stockinstrumenthistory',
            options={'verbose_name': 'تاریخچه', 'verbose_name_plural': '۱۳) تاریخچه\u200cها'},
        ),
    ]
