# Generated by Django 5.0.1 on 2024-05-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0014_alter_stockindustrialgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockcompany',
            options={'verbose_name': 'شرکت', 'verbose_name_plural': '۲۱) شرکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='stockmonthlyactivityreport',
            options={'verbose_name': 'گزارش\u200c فعالیت ماهانه', 'verbose_name_plural': '۲۲) گزارش\u200cهای فعالیت\u200c ماهانه'},
        ),
    ]
