# Generated by Django 5.0.1 on 2024-05-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0015_alter_stockcompany_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcompany',
            name='codal_st',
        ),
        migrations.AddField(
            model_name='stockcompany',
            name='publisher_state',
            field=models.IntegerField(default=-1, verbose_name='وضعیت ناشر'),
            preserve_default=False,
        ),
    ]
