# Generated by Django 5.0.1 on 2024-05-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0016_remove_stockcompany_codal_st_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockCompany',
            new_name='CodalCompany',
        ),
        migrations.AlterModelOptions(
            name='codalcompany',
            options={'verbose_name': 'شرکت کدال', 'verbose_name_plural': '۲۱) شرکت\u200cهای کدال'},
        ),
    ]
