# Generated by Django 5.0.1 on 2024-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0017_rename_stockcompany_codalcompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codalcompany',
            name='publisher_state',
            field=models.IntegerField(choices=[(0, 'پذیرفته شده در بورس تهران'), (1, 'پذیرفته شده در فرابورس ایران'), (2, 'ثبت شده پذیرفته نشده'), (3, 'ثبت نشده نزد سازمان'), (4, 'پذیرفته شده در بورس کالای ایران'), (5, 'پذیرفته شده دربورس انرژی ایران')], verbose_name='وضعیت ناشر'),
        ),
    ]
