# Generated by Django 5.0.1 on 2024-05-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0018_alter_codalcompany_publisher_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockMonthlyActivityReport',
            new_name='CodalMonthlyActivityReport',
        ),
    ]
