# Generated by Django 5.0.1 on 2024-06-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0020_stockinstrumentadjustedhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinstrumentadjustedhistory',
            name='is_last_adjustmen',
            field=models.BooleanField(default=False, verbose_name='آخرین تعدیل'),
        ),
    ]
