# Generated by Django 5.0.1 on 2024-06-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0021_stockinstrumentadjustedhistory_is_last_adjustmen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinstrumentadjustedhistory',
            old_name='is_last_adjustmen',
            new_name='is_last_adjustment',
        ),
    ]
