# Generated by Django 5.0.1 on 2024-06-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0022_rename_is_last_adjustmen_stockinstrumentadjustedhistory_is_last_adjustment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinstrumentadjustedhistory',
            old_name='is_last_adjustment',
            new_name='is_adjusted',
        ),
    ]
