# Generated by Django 5.0.1 on 2024-06-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0023_rename_is_last_adjustment_stockinstrumentadjustedhistory_is_adjusted'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInstrumentPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateField(verbose_name='تاریخ')),
                ('trade_count', models.IntegerField(verbose_name='تعداد معاملات')),
                ('volume', models.BigIntegerField(verbose_name='حجم معاملات')),
                ('value', models.BigIntegerField(verbose_name='ارزش معاملات')),
                ('yesterday_price', models.IntegerField(verbose_name='قیمت دیروز')),
                ('open', models.IntegerField(verbose_name='اولین قیمت')),
                ('close', models.IntegerField(verbose_name='آخرین قیمت')),
                ('low', models.IntegerField(verbose_name='کمترین قیمت')),
                ('high', models.IntegerField(verbose_name='بیشترین قیمت')),
                ('close_mean', models.IntegerField(verbose_name='قیمت پایانی')),
                ('is_adjusted', models.BooleanField(default=False, verbose_name='تعدیل شده')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stock_market.stockinstrument', verbose_name='نماد')),
            ],
            options={
                'verbose_name': 'تاریخچه قیمت (تعدیل شده)',
                'verbose_name_plural': '۱۴) تاریخچه\u200cهای قمیت (تعدیل شده)',
                'unique_together': {('instrument', 'trade_date')},
            },
        ),
    ]
