# Generated by Django 5.0.1 on 2024-06-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0024_stockinstrumentpricehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinstrumentpricehistory',
            name='is_adjusted',
        ),
    ]
