# Generated by Django 5.0.1 on 2024-06-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0025_remove_stockinstrumentpricehistory_is_adjusted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockinstrumentpricehistory',
            options={'verbose_name': 'تاریخچه قیمت', 'verbose_name_plural': '۱۴) تاریخچه\u200cهای قمیت'},
        ),
        migrations.CreateModel(
            name='StockInstrumentILHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateField(verbose_name='تاریخ')),
                ('individual_buy_count', models.IntegerField(verbose_name='تعداد خرید حقیقی')),
                ('individual_buy_volume', models.BigIntegerField(verbose_name='حجم خرید حقیقی')),
                ('individual_buy_value', models.BigIntegerField(verbose_name='ارزش خرید حقیقی')),
                ('legal_buy_count', models.IntegerField(verbose_name='تعداد خرید حقوقی')),
                ('legal_buy_volume', models.BigIntegerField(verbose_name='حجم خرید حقوقی')),
                ('legal_buy_value', models.BigIntegerField(verbose_name='ارزش خرید حقوقی')),
                ('individual_sell_count', models.IntegerField(verbose_name='تعداد فروش حقیقی')),
                ('individual_sell_volume', models.BigIntegerField(verbose_name='حجم فروش حقیقی')),
                ('individual_sell_value', models.BigIntegerField(verbose_name='ارزش فروش حقیقی')),
                ('legal_sell_count', models.IntegerField(verbose_name='تعداد فروش حقوقی')),
                ('legal_sell_volume', models.BigIntegerField(verbose_name='حجم فروش حقوقی')),
                ('legal_sell_value', models.BigIntegerField(verbose_name='ارزش فروش حقوقی')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='il_history', to='stock_market.stockinstrument', verbose_name='نماد')),
            ],
            options={
                'verbose_name': 'تاریخچه',
                'verbose_name_plural': '۱۳) تاریخچه\u200cها',
                'unique_together': {('instrument', 'trade_date')},
            },
        ),
    ]
