# Generated by Django 5.0.1 on 2024-06-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0026_alter_stockinstrumentpricehistory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockInstrumentHistory',
        ),
    ]
