# Generated by Django 5.0.1 on 2024-06-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0027_delete_stockinstrumenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockinstrumentadjustedhistory',
            options={'verbose_name': 'تاریخچه (تعدیل شده)', 'verbose_name_plural': '۱۵) تاریخچه\u200cها (تعدیل شده)'},
        ),
        migrations.AlterModelOptions(
            name='stockinstrumentilhistory',
            options={'verbose_name': 'تاریخچه حقیقی حقوقی', 'verbose_name_plural': '۱۴) تاریخچه\u200cهای حقیقی حقوقی'},
        ),
        migrations.AlterModelOptions(
            name='stockinstrumentpricehistory',
            options={'verbose_name': 'تاریخچه قیمت', 'verbose_name_plural': '۱۳) تاریخچه\u200cهای قمیت'},
        ),
    ]
