# Generated by Django 5.0.1 on 2024-06-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0029_stockadjustedpricehistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustedpricehistory',
            name='is_adjusted',
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='individual_buy_count',
            field=models.IntegerField(default=0, verbose_name='تعداد خرید حقیقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='individual_buy_value',
            field=models.BigIntegerField(default=0, verbose_name='ارزش خرید حقیقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='individual_buy_volume',
            field=models.BigIntegerField(default=0, verbose_name='حجم خرید حقیقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='individual_sell_count',
            field=models.IntegerField(default=1, verbose_name='تعداد فروش حقیقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='individual_sell_value',
            field=models.BigIntegerField(default=1, verbose_name='ارزش فروش حقیقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='individual_sell_volume',
            field=models.BigIntegerField(default=1, verbose_name='حجم فروش حقیقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='legal_buy_count',
            field=models.IntegerField(default=1, verbose_name='تعداد خرید حقوقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='legal_buy_value',
            field=models.BigIntegerField(default=1, verbose_name='ارزش خرید حقوقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='legal_buy_volume',
            field=models.BigIntegerField(default=1, verbose_name='حجم خرید حقوقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='legal_sell_count',
            field=models.IntegerField(default=1, verbose_name='تعداد فروش حقوقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='legal_sell_value',
            field=models.BigIntegerField(default=1, verbose_name='ارزش فروش حقوقی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustedpricehistory',
            name='legal_sell_volume',
            field=models.BigIntegerField(default=1, verbose_name='حجم فروش حقوقی'),
            preserve_default=False,
        ),
    ]
