# Generated by Django 5.0.1 on 2024-06-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0030_remove_stockadjustedpricehistory_is_adjusted_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockAdjustedPriceHistory',
            new_name='StockAdjustedHistory',
        ),
    ]
