# Generated by Django 5.0.1 on 2024-06-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0032_alter_stockinstrumentpricehistory_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockHistory',
            new_name='StockRawHistory',
        ),
    ]
