# Generated by Django 5.0.1 on 2024-06-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0033_rename_stockhistory_stockrawhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockAdjustedHistory',
        ),
    ]
