# Generated by Django 5.0.1 on 2024-06-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0034_delete_stockadjustedhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrawhistory',
            options={'verbose_name': 'تاریخچه قیمت (تعدیل نشده)', 'verbose_name_plural': '۱۳) تاریخچه\u200c قمیت\u200cها (تعدیل نشده)'},
        ),
    ]
