# Generated by Django 5.0.1 on 2024-07-01 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_market", "0035_alter_stockrawhistory_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, null=True, verbose_name="نام تنظیمات پیشنهاد سهم"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PutValueChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=False, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=-100000, verbose_name="مقدار آستانه"),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="put_value_change",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OptionPriceSpread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=True, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=-100000, verbose_name="مقدار آستانه"),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_price_spread",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MoneyFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=True, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=-100000, verbose_name="مقدار آستانه"),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_flow",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GlobalPositiveRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=True, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=0, verbose_name="مقدار آستانه"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        choices=[
                            (7, "هفتگی"),
                            (30, "ماهانه"),
                            (90, "سه\u200c ماهه"),
                            (180, "شش\u200c ماهه"),
                            (365, "یک\u200c ساله"),
                        ],
                        default=90,
                        verbose_name="وزن",
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_positive_range",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GlobalNegativeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=False, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=0, verbose_name="مقدار آستانه"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        choices=[
                            (7, "هفتگی"),
                            (30, "ماهانه"),
                            (90, "سه\u200c ماهه"),
                            (180, "شش\u200c ماهه"),
                            (365, "یک\u200c ساله"),
                        ],
                        default=90,
                        verbose_name="وزن",
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_negative_range",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomesticPositiveRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=True, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=0, verbose_name="مقدار آستانه"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        choices=[
                            (7, "هفتگی"),
                            (30, "ماهانه"),
                            (90, "سه\u200c ماهه"),
                            (180, "شش\u200c ماهه"),
                            (365, "یک\u200c ساله"),
                        ],
                        default=90,
                        verbose_name="وزن",
                    ),
                ),
                (
                    "min_commodity_ratio",
                    models.IntegerField(
                        default=0, verbose_name="حداقل مقدار نسبت محصول"
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_positive_range",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DomesticNegativeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=False, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=0, verbose_name="مقدار آستانه"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        choices=[
                            (7, "هفتگی"),
                            (30, "ماهانه"),
                            (90, "سه\u200c ماهه"),
                            (180, "شش\u200c ماهه"),
                            (365, "یک\u200c ساله"),
                        ],
                        default=90,
                        verbose_name="وزن",
                    ),
                ),
                (
                    "min_commodity_ratio",
                    models.IntegerField(
                        default=0, verbose_name="حداقل مقدار نسبت محصول"
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_negative_range",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CallValueChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=True, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=-100000, verbose_name="مقدار آستانه"),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_value_change",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=True, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=0, verbose_name="مقدار آستانه"),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_value",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuyRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=True, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=0, verbose_name="مقدار آستانه"),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_ratio",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuyPressure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=True, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=0, verbose_name="مقدار آستانه"),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_pressure",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ROI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=False, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=-100000, verbose_name="مقدار آستانه"),
                ),
                (
                    "duration",
                    models.IntegerField(
                        choices=[
                            (7, "هفتگی"),
                            (30, "ماهانه"),
                            (90, "سه\u200c ماهه"),
                            (180, "شش\u200c ماهه"),
                            (365, "یک\u200c ساله"),
                            (1095, "سه\u200c ساله"),
                        ],
                        default=90,
                        verbose_name="وزن",
                    ),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roi",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SellRatio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=False, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=0, verbose_name="مقدار آستانه"),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_ratio",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ValueChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_enabled", models.BooleanField(default=False, verbose_name="فعال")),
                ("ascending", models.BooleanField(default=True, verbose_name="ترتیب")),
                ("weight", models.IntegerField(default=5, verbose_name="وزن")),
                (
                    "threshold_value",
                    models.IntegerField(default=-100000, verbose_name="مقدار آستانه"),
                ),
                (
                    "recommendation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value_change",
                        to="stock_market.recommendationconfig",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
