# Generated by Django 5.0.1 on 2024-07-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_market", "0036_recommendationconfig_putvaluechange_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recommendationconfig",
            options={
                "verbose_name": "تنظیمات پیشنهاد سهم",
                "verbose_name_plural": "۳۱) تنظیمات پیشنهاد سهم",
            },
        ),
        migrations.AddField(
            model_name="recommendationconfig",
            name="is_deafult",
            field=models.BooleanField(
                default=False, verbose_name="تنظیمات پیش\u200cفرض"
            ),
        ),
        migrations.AlterField(
            model_name="buypressure",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="buyratio",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="buyvalue",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="callvaluechange",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="domesticnegativerange",
            name="ascending",
            field=models.BooleanField(default=False, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="domesticpositiverange",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="globalnegativerange",
            name="ascending",
            field=models.BooleanField(default=False, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="globalpositiverange",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="moneyflow",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="optionpricespread",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="putvaluechange",
            name="ascending",
            field=models.BooleanField(default=False, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="roi",
            name="ascending",
            field=models.BooleanField(default=False, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="sellratio",
            name="ascending",
            field=models.BooleanField(default=False, verbose_name="صعودی"),
        ),
        migrations.AlterField(
            model_name="valuechange",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="صعودی"),
        ),
    ]
