# Generated by Django 5.0.1 on 2024-07-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_market", "0037_alter_recommendationconfig_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recommendationconfig",
            old_name="is_deafult",
            new_name="is_default",
        ),
    ]
