# Generated by Django 5.0.1 on 2024-07-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_market", "0038_rename_is_deafult_recommendationconfig_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendationconfig",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="پیش\u200cفرض"),
        ),
    ]
