# Generated by Django 5.0.1 on 2024-07-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_market", "0039_alter_recommendationconfig_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="buypressure",
            name="name",
            field=models.CharField(
                default="buy_presure", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buyratio",
            name="name",
            field=models.CharField(
                default="buy_ratio", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buyvalue",
            name="name",
            field=models.CharField(
                default="buy_value", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="callvaluechange",
            name="name",
            field=models.CharField(
                default="call_value_change", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="domesticnegativerange",
            name="name",
            field=models.CharField(
                default="domestic_negative_range", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="domesticpositiverange",
            name="name",
            field=models.CharField(
                default="domestic_positive_range", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="globalnegativerange",
            name="name",
            field=models.CharField(
                default="global_negative_range", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="globalpositiverange",
            name="name",
            field=models.CharField(
                default="global_positive_range", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moneyflow",
            name="name",
            field=models.CharField(
                default="money_flow", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="optionpricespread",
            name="name",
            field=models.CharField(
                default="option_price_spread", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="putvaluechange",
            name="name",
            field=models.CharField(
                default="put_value_change", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roi",
            name="name",
            field=models.CharField(default="roi", max_length=255, verbose_name="نام"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sellratio",
            name="name",
            field=models.CharField(
                default="sell_ratio", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="valuechange",
            name="name",
            field=models.CharField(
                default="value_change", max_length=255, verbose_name="نام"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recommendationconfig",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="نام تنظیمات پیشنهاد سهم",
            ),
        ),
    ]
