# Generated by Django 5.0.1 on 2024-07-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_market", "0040_buypressure_name_buyratio_name_buyvalue_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buypressure",
            name="name",
        ),
        migrations.RemoveField(
            model_name="buyratio",
            name="name",
        ),
        migrations.RemoveField(
            model_name="buyvalue",
            name="name",
        ),
        migrations.RemoveField(
            model_name="callvaluechange",
            name="name",
        ),
        migrations.RemoveField(
            model_name="domesticnegativerange",
            name="name",
        ),
        migrations.RemoveField(
            model_name="domesticpositiverange",
            name="name",
        ),
        migrations.RemoveField(
            model_name="globalnegativerange",
            name="name",
        ),
        migrations.RemoveField(
            model_name="globalpositiverange",
            name="name",
        ),
        migrations.RemoveField(
            model_name="moneyflow",
            name="name",
        ),
        migrations.RemoveField(
            model_name="optionpricespread",
            name="name",
        ),
        migrations.RemoveField(
            model_name="putvaluechange",
            name="name",
        ),
        migrations.RemoveField(
            model_name="roi",
            name="name",
        ),
        migrations.RemoveField(
            model_name="sellratio",
            name="name",
        ),
        migrations.RemoveField(
            model_name="valuechange",
            name="name",
        ),
    ]
