# Generated by Django 5.0.1 on 2024-07-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_market", "0041_remove_buypressure_name_remove_buyratio_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buypressure",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="buypressure",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buy_pressure",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="buypressure",
            name="weight",
            field=models.IntegerField(default=6, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="buyratio",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="buyratio",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buy_ratio",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="buyratio",
            name="weight",
            field=models.IntegerField(default=6, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="buyvalue",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="buyvalue",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buy_value",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="buyvalue",
            name="weight",
            field=models.IntegerField(default=6, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="callvaluechange",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="callvaluechange",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_value_change",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="callvaluechange",
            name="weight",
            field=models.IntegerField(default=6, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="domesticnegativerange",
            name="ascending",
            field=models.BooleanField(default=False, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="domesticnegativerange",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (7, "هفتگی"),
                    (30, "ماهانه"),
                    (90, "سه\u200c ماهه"),
                    (180, "شش\u200c ماهه"),
                    (365, "یک\u200c ساله"),
                ],
                default=30,
                verbose_name="دوره عمکلرد",
            ),
        ),
        migrations.AlterField(
            model_name="domesticnegativerange",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domestic_negative_range",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="domesticnegativerange",
            name="weight",
            field=models.IntegerField(default=10, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="domesticpositiverange",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="domesticpositiverange",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (7, "هفتگی"),
                    (30, "ماهانه"),
                    (90, "سه\u200c ماهه"),
                    (180, "شش\u200c ماهه"),
                    (365, "یک\u200c ساله"),
                ],
                default=30,
                verbose_name="دوره عملکرد",
            ),
        ),
        migrations.AlterField(
            model_name="domesticpositiverange",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domestic_positive_range",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="domesticpositiverange",
            name="weight",
            field=models.IntegerField(default=10, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="globalnegativerange",
            name="ascending",
            field=models.BooleanField(default=False, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="globalnegativerange",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (7, "هفتگی"),
                    (30, "ماهانه"),
                    (90, "سه\u200c ماهه"),
                    (180, "شش\u200c ماهه"),
                    (365, "یک\u200c ساله"),
                ],
                default=30,
                verbose_name="دوره عملکرد",
            ),
        ),
        migrations.AlterField(
            model_name="globalnegativerange",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="global_negative_range",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="globalnegativerange",
            name="weight",
            field=models.IntegerField(default=10, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="globalpositiverange",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="globalpositiverange",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (7, "هفتگی"),
                    (30, "ماهانه"),
                    (90, "سه\u200c ماهه"),
                    (180, "شش\u200c ماهه"),
                    (365, "یک\u200c ساله"),
                ],
                default=30,
                verbose_name="دوره عملکرد",
            ),
        ),
        migrations.AlterField(
            model_name="globalpositiverange",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="global_positive_range",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="globalpositiverange",
            name="weight",
            field=models.IntegerField(default=10, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="moneyflow",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="moneyflow",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="money_flow",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="moneyflow",
            name="weight",
            field=models.IntegerField(default=6, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="optionpricespread",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="optionpricespread",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_price_spread",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="optionpricespread",
            name="weight",
            field=models.IntegerField(default=6, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="putvaluechange",
            name="ascending",
            field=models.BooleanField(default=False, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="putvaluechange",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="put_value_change",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="putvaluechange",
            name="weight",
            field=models.IntegerField(default=6, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="roi",
            name="ascending",
            field=models.BooleanField(default=False, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="roi",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (7, "هفتگی"),
                    (30, "ماهانه"),
                    (90, "سه\u200c ماهه"),
                    (180, "شش\u200c ماهه"),
                    (365, "یک\u200c ساله"),
                    (1095, "سه\u200c ساله"),
                ],
                default=90,
                verbose_name="دوره عملکرد",
            ),
        ),
        migrations.AlterField(
            model_name="roi",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roi",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="roi",
            name="weight",
            field=models.IntegerField(default=6, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="sellratio",
            name="ascending",
            field=models.BooleanField(default=False, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="sellratio",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sell_ratio",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="sellratio",
            name="weight",
            field=models.IntegerField(default=6, verbose_name="وزن"),
        ),
        migrations.AlterField(
            model_name="valuechange",
            name="ascending",
            field=models.BooleanField(default=True, verbose_name="رابطه مستقیم"),
        ),
        migrations.AlterField(
            model_name="valuechange",
            name="recommendation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="value_change",
                to="stock_market.recommendationconfig",
                verbose_name="کانفیگ",
            ),
        ),
        migrations.AlterField(
            model_name="valuechange",
            name="weight",
            field=models.IntegerField(default=6, verbose_name="وزن"),
        ),
    ]
