# Generated by Django 5.0.1 on 2024-08-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0042_alter_buypressure_ascending_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockinstrument',
            constraint=models.UniqueConstraint(fields=('id',), name='stock_instrument_unique_id'),
        ),
    ]
