# Generated by Django 5.0.1 on 2024-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0043_stockinstrument_stock_instrument_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buypressure',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='marketwatch', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='buyratio',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='marketwatch', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='buyvalue',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='marketwatch', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='callvaluechange',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='marketwatch', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='domesticnegativerange',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='foundamental', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='domesticpositiverange',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='foundamental', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='globalnegativerange',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='foundamental', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='globalpositiverange',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='foundamental', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='moneyflow',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='marketwatch', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='optionpricespread',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='marketwatch', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='putvaluechange',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='marketwatch', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='roi',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='marketwatch', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='sellratio',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='marketwatch', verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='valuechange',
            name='category',
            field=models.CharField(choices=[('foundamental', 'بنیادی'), ('marketwatch', 'تابلوخوانی')], default='marketwatch', verbose_name='نوع'),
        ),
    ]
