# Generated by Django 5.0.1 on 2024-08-21 07:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0044_buypressure_category_buyratio_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendationconfig',
            unique_together={('user', 'is_default')},
        ),
    ]
