# Generated by Django 5.0.1 on 2024-08-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0045_alter_recommendationconfig_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendationconfig',
            unique_together=set(),
        ),
    ]
