# Generated by Django 5.0.1 on 2024-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0046_alter_recommendationconfig_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='codalcompany',
            name='codal_IG',
            field=models.IntegerField(blank=True, null=True, verbose_name='فیلد IG'),
        ),
        migrations.AddField(
            model_name='codalcompany',
            name='codal_RT',
            field=models.IntegerField(blank=True, null=True, verbose_name='فیلد RT'),
        ),
        migrations.AlterField(
            model_name='codalcompany',
            name='codal_t',
            field=models.IntegerField(blank=True, null=True, verbose_name='فیلد t'),
        ),
    ]
