# Generated by Django 5.0.1 on 2025-03-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0047_codalcompany_codal_ig_codalcompany_codal_rt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockindustrialgroup',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='اولویت'),
            preserve_default=False,
        ),
    ]
