# Generated by Django 5.0.1 on 2025-03-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market', '0048_stockindustrialgroup_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockindustrialgroup',
            name='priority',
            field=models.IntegerField(default=99, verbose_name='اولویت'),
        ),
    ]
