# Generated by Django 5.0.1 on 2024-03-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticCommodityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='نوع کالا')),
                ('code', models.CharField(max_length=255, verbose_name='کد نوع کالا')),
            ],
            options={
                'verbose_name': 'نوع کالا',
                'verbose_name_plural': 'انواع کالا',
            },
        ),
        migrations.CreateModel(
            name='DomesticIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام صنعت')),
                ('code', models.CharField(max_length=255, verbose_name='کد صنعت')),
            ],
            options={
                'verbose_name': 'صنعت',
                'verbose_name_plural': 'صنایع',
            },
        ),
        migrations.CreateModel(
            name='DomesticCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('code', models.CharField(max_length=255, verbose_name='کد کالا')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='domestic_market.domesticcommoditytype', verbose_name='نوع کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.AddField(
            model_name='domesticcommoditytype',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_types', to='domestic_market.domesticindustry', verbose_name='صنعت'),
        ),
    ]
