# Generated by Django 5.0.1 on 2024-03-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='تولید کننده')),
                ('code', models.IntegerField(verbose_name='کد تولید کننده')),
            ],
            options={
                'verbose_name': 'تولید کننده',
                'verbose_name_plural': 'تولید کننده\u200cها',
            },
        ),
        migrations.AlterField(
            model_name='domesticcommodity',
            name='code',
            field=models.IntegerField(verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='domesticcommoditytype',
            name='code',
            field=models.IntegerField(verbose_name='کد نوع کالا'),
        ),
        migrations.AlterField(
            model_name='domesticindustry',
            name='code',
            field=models.IntegerField(verbose_name='کد صنعت'),
        ),
    ]
