# Generated by Django 5.0.1 on 2024-03-03 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0002_domesticproducer_alter_domesticcommodity_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_date', models.DateField(verbose_name='تاریخ معامله')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_market.domesticcommodity', verbose_name='کالا')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_market.domesticproducer', verbose_name='تولید کننده')),
            ],
            options={
                'verbose_name': 'معامله',
                'verbose_name_plural': 'معاملات',
            },
        ),
    ]
