# Generated by Django 5.0.1 on 2024-03-03 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0003_domestictrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domestictrade',
            name='price',
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='base_price',
            field=models.BigIntegerField(default=1, verbose_name='قیمت پایه عرضه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='close_price',
            field=models.BigIntegerField(default=1, verbose_name='قیمت میانگین پایانی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='competition',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='رقابت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='contract_type',
            field=models.CharField(default='aaa', max_length=200, verbose_name='نوع قرارداد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ تحویل'),
            preserve_default=False,
        ),
    ]
