# Generated by Django 5.0.1 on 2024-03-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0004_remove_domestictrade_price_domestictrade_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestictrade',
            name='value',
            field=models.BigIntegerField(default=1, verbose_name='ارزش معامله'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domestictrade',
            name='competition',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='درصد رقابت'),
        ),
    ]
