# Generated by Django 5.0.1 on 2024-03-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0005_domestictrade_value_alter_domestictrade_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestictrade',
            name='commodity_name',
            field=models.CharField(default='aasa', max_length=255, verbose_name='نام کالا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='currency',
            field=models.CharField(default='asas', max_length=255, verbose_name='ارز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='max',
            field=models.BigIntegerField(default=1, verbose_name='حداکثر قیمت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='min_price',
            field=models.BigIntegerField(default=1, verbose_name='حداقل قیمت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='symbol',
            field=models.CharField(default='aa', max_length=255, verbose_name='نماد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='unit',
            field=models.CharField(default='asa', max_length=255, verbose_name='واحد'),
            preserve_default=False,
        ),
    ]
