# Generated by Django 5.0.1 on 2024-03-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0006_domestictrade_commodity_name_domestictrade_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domestictrade',
            old_name='max',
            new_name='max_price',
        ),
    ]
