# Generated by Django 5.0.1 on 2024-03-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0007_rename_max_domestictrade_max_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestictrade',
            name='trade_date_shamsi',
            field=models.CharField(default='', max_length=255, verbose_name='تاریخ شمسی معامله'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domestictrade',
            name='trade_date',
            field=models.DateField(verbose_name='تاریخ میلادی معامله'),
        ),
    ]
