# Generated by Django 5.0.1 on 2024-03-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0008_domestictrade_trade_date_shamsi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradesHistoryFetch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.CharField(verbose_name='از تاریخ')),
                ('end_date', models.CharField(verbose_name='تا تاریخ')),
                ('request_sent', models.BooleanField(verbose_name='ارسال درخواست')),
                ('received_trades', models.BooleanField(default=False, verbose_name='دریافت اطلاعات')),
                ('start_populating_db', models.BooleanField(default=False, verbose_name='شروع ثبت در دیتابیس')),
                ('db_populated', models.BooleanField(default=False, verbose_name='اتمام ثبت در دیتابیس')),
                ('number_of_trades_received', models.IntegerField(default=0, verbose_name='رکوردهای دریافت شده')),
                ('number_of_populated_trades', models.IntegerField(default=0, verbose_name='رکوردهای ثبت شده')),
            ],
            options={
                'verbose_name': 'تاریخچه دریافت اطلاعات بورس کالا',
                'verbose_name_plural': 'تاریخچه دریافت اطلاعات بورس کالا',
            },
        ),
    ]
