# Generated by Django 5.0.1 on 2024-03-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0009_tradeshistoryfetch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradesHistoryFetch',
            new_name='DomesticTradesHistoryFetch',
        ),
    ]
