# Generated by Django 5.0.1 on 2024-03-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0010_rename_tradeshistoryfetch_domestictradeshistoryfetch'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticDollarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True, verbose_name='تاریخ میلادی')),
                ('date_shamsi', models.CharField(unique=True, verbose_name='تاریخ شمسی')),
                ('nima', models.IntegerField(verbose_name='نرخ نیمایی')),
                ('azad', models.IntegerField(verbose_name='نرخ آزاد')),
            ],
            options={
                'verbose_name': 'قیمت دلار',
                'verbose_name_plural': 'قیمت\u200cهای دلار',
            },
        ),
    ]
