# Generated by Django 5.0.1 on 2024-03-04 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0011_domesticdollarprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticFavoritePriceChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domestic_market.domesticcommodity', verbose_name='کالا')),
                ('commodity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_market.domesticcommoditytype', verbose_name='نوع کالا')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_market.domesticindustry', verbose_name='صنعت')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domestic_market.domesticproducer', verbose_name='تولید کننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_price_charts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نمودار قیمت مورد علاقه',
                'verbose_name_plural': 'نمودارهای قیمت مورد علاقه',
                'unique_together': {('user', 'industry', 'commodity_type', 'commodity', 'producer')},
            },
        ),
    ]
