# Generated by Django 5.0.1 on 2024-03-04 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0012_domesticfavoritepricechart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticFavoriteRatioChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_commodity_1', to='domestic_market.domesticcommodity', verbose_name='کالا ۱')),
                ('commodity_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_commodity_2', to='domestic_market.domesticcommodity', verbose_name='کالا ۲')),
                ('commodity_type_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_commodity_type_1', to='domestic_market.domesticcommoditytype', verbose_name='نوع کالا ۱')),
                ('commodity_type_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_commodity_type_2', to='domestic_market.domesticcommoditytype', verbose_name='نوع کالا ۲')),
                ('industry_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_industry_1', to='domestic_market.domesticindustry', verbose_name='صنعت ۱')),
                ('industry_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_industry_2', to='domestic_market.domesticindustry', verbose_name='صنعت ۲')),
                ('producer_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_transit_1', to='domestic_market.domesticproducer', verbose_name='تولید کننده ۱')),
                ('producer_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_transit_2', to='domestic_market.domesticproducer', verbose_name='تولید کننده ۲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_charts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نسبت قیمت مورد علاقه',
                'verbose_name_plural': 'نسبت\u200cهای قیمت مورد علاقه',
                'unique_together': {('user', 'industry_1', 'commodity_type_1', 'commodity_1', 'producer_1', 'industry_2', 'commodity_type_2', 'commodity_2', 'producer_2')},
            },
        ),
    ]
