# Generated by Django 5.0.1 on 2024-04-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0013_domesticfavoriteratiochart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domestictrade',
            name='max_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='حداکثر قیمت'),
        ),
        migrations.AlterField(
            model_name='domestictrade',
            name='min_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='حداقل قیمت'),
        ),
    ]
