# Generated by Django 5.0.1 on 2024-04-13 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0015_domesticmonthlysell'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticFavoritePriceChartByProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_market.domesticcommodity', verbose_name='کالا')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_market.domesticproducer', verbose_name='تولید کننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_price_charts_by_producer', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نمودار قیمت مورد علاقه بر اساس تولید کننده',
                'verbose_name_plural': 'نمودارهای قیمت مورد علاقه بر اساس تولید کننده',
                'unique_together': {('user', 'producer', 'commodity')},
            },
        ),
    ]
