# Generated by Django 5.0.1 on 2024-04-13 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0016_domesticfavoritepricechartbyproducer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticFavoriteRatioChartByProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodity_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_by_producer_commodity_1', to='domestic_market.domesticcommodity', verbose_name='کالا ۱')),
                ('commodity_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_by_producer_commodity_2', to='domestic_market.domesticcommodity', verbose_name='کالا ۲')),
                ('producer_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_by_producer_1', to='domestic_market.domesticproducer', verbose_name='تولید کننده ۱')),
                ('producer_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_by_producer_2', to='domestic_market.domesticproducer', verbose_name='تولید کننده ۲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_ratio_charts_by_producer', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نسبت قیمت مورد علاقه بر اساس تولید کننده',
                'verbose_name_plural': 'نسبت\u200cهای قیمت مورد علاقه بر اساس تولید کننده',
                'unique_together': {('user', 'producer_1', 'commodity_1', 'producer_2', 'commodity_2')},
            },
        ),
    ]
