# Generated by Django 5.0.1 on 2024-04-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0017_domesticfavoriteratiochartbyproducer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DomesticMonthlySell',
        ),
    ]
