# Generated by Django 5.0.1 on 2024-04-21 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0018_delete_domesticmonthlysell'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticMonthlySell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='تاریخ میلادی ابتدای ماه')),
                ('end_date', models.DateField(verbose_name='تاریخ میلادی آخر ماه')),
                ('min_value', models.BigIntegerField(verbose_name='حداقل ارزش ماهانه')),
                ('max_value', models.BigIntegerField(verbose_name='حداکثر ارزش ماهانه')),
                ('mean_value', models.BigIntegerField(verbose_name='میانگین ارزش ماهانه')),
                ('total_value', models.BigIntegerField(verbose_name='کل ارزش ماهانه')),
                ('commodity_name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('symbol', models.CharField(max_length=255, verbose_name='نماد')),
                ('monthly_min_base_price', models.BigIntegerField(verbose_name='کمترین قیمت پایه عرضه ماه')),
                ('monthly_max_base_price', models.BigIntegerField(verbose_name='بیشترین قیمت پایه عرضه ماه')),
                ('monthly_mean_base_price', models.BigIntegerField(verbose_name='میانگین قیمت پایه عرضه ماه')),
                ('monthly_min_price', models.BigIntegerField(blank=True, null=True, verbose_name='حداقل قیمت ماه')),
                ('monthly_max_price', models.BigIntegerField(blank=True, null=True, verbose_name='حداکثر قیمت ماه')),
                ('monthly_mean_price', models.BigIntegerField(blank=True, null=True, verbose_name='میانگین قیمت ماه')),
                ('monthly_min_close_price', models.BigIntegerField(verbose_name='کمترین قیمت میانگین پایانی ماه')),
                ('monthly_max_close_price', models.BigIntegerField(verbose_name='بیشترین قیمت میانگین پایانی ماه')),
                ('monthly_mean_close_price', models.BigIntegerField(verbose_name='میانگین قیمت میانگین پایانی ماه')),
                ('unit', models.CharField(max_length=255, verbose_name='واحد')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_market.domesticcommodity', verbose_name='کالا')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_market.domesticproducer', verbose_name='تولید کننده')),
            ],
            options={
                'verbose_name': 'فروش ماهانه',
                'verbose_name_plural': 'فروش ماهانه',
            },
        ),
    ]
