# Generated by Django 5.0.1 on 2024-04-21 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0019_domesticmonthlysell'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticFavoriteProducerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domestic_market.domesticproducer', verbose_name='تولید کننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_favorite_producer_report', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تولید کننده مورد علاقه برای گزارش',
                'verbose_name_plural': 'تولید کننده مورد علاقه برای گزارش',
                'unique_together': {('user', 'producer')},
            },
        ),
    ]
