# Generated by Django 5.0.1 on 2024-04-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0021_domesticfavoriteproducersell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BourseViewCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cookie', models.TextField(verbose_name='کوکی')),
            ],
            options={
                'verbose_name': 'آکوکی',
                'verbose_name_plural': 'آکوکی',
            },
        ),
    ]
