# Generated by Django 5.0.1 on 2024-04-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0023_alter_domesticfavoritepricechartbyproducer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bourseviewcookie',
            options={'verbose_name': 'کوکی', 'verbose_name_plural': '8: کوکی'},
        ),
        migrations.AlterModelOptions(
            name='domesticcommodity',
            options={'verbose_name': 'کالا', 'verbose_name_plural': '3: کالاها'},
        ),
        migrations.AlterModelOptions(
            name='domesticcommoditytype',
            options={'verbose_name': 'نوع کالا', 'verbose_name_plural': '2: انواع کالا'},
        ),
        migrations.AlterModelOptions(
            name='domesticdollarprice',
            options={'verbose_name': 'قیمت دلار', 'verbose_name_plural': '7: قیمت\u200cهای دلار'},
        ),
        migrations.AlterModelOptions(
            name='domesticindustry',
            options={'verbose_name': 'صنعت', 'verbose_name_plural': '1: صنایع'},
        ),
        migrations.AlterModelOptions(
            name='domesticmonthlysell',
            options={'verbose_name': 'فروش ماهانه', 'verbose_name_plural': '6: فروش ماهانه'},
        ),
        migrations.AlterModelOptions(
            name='domesticproducer',
            options={'verbose_name': 'تولید کننده', 'verbose_name_plural': '4: تولید کننده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='domestictrade',
            options={'verbose_name': 'معامله', 'verbose_name_plural': '5: معاملات'},
        ),
        migrations.AlterModelOptions(
            name='domestictradeshistoryfetch',
            options={'verbose_name': 'تاریخچه دریافت اطلاعات بورس کالا', 'verbose_name_plural': '9: تاریخچه دریافت اطلاعات بورس کالا'},
        ),
    ]
