# Generated by Django 5.0.1 on 2024-04-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0024_alter_bourseviewcookie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestictrade',
            name='broker',
            field=models.CharField(default='broker name', max_length=255, verbose_name='کارگزار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='contract_volume',
            field=models.DecimalField(decimal_places=2, default=12.1, max_digits=20, verbose_name='حجم قرارداد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='demand_volume',
            field=models.DecimalField(decimal_places=2, default=12.1, max_digits=20, verbose_name='حجم تقاضا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domestictrade',
            name='supply_volume',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=20, verbose_name='حجم عرضه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domestictrade',
            name='value',
            field=models.BigIntegerField(verbose_name='ارزش معامله (هزار ریال)'),
        ),
    ]
