# Generated by Django 5.0.1 on 2024-04-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0025_domestictrade_broker_domestictrade_contract_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestictrade',
            name='delivery_date_shamsi',
            field=models.CharField(default='asas', max_length=255, verbose_name='تاریخ شمسی تحویل'),
            preserve_default=False,
        ),
    ]
