# Generated by Django 5.0.1 on 2024-05-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0026_domestictrade_delivery_date_shamsi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bourseviewcookie',
            options={'verbose_name': 'کوکی', 'verbose_name_plural': '۸) کوکی'},
        ),
        migrations.AlterModelOptions(
            name='domesticcommodity',
            options={'verbose_name': 'کالا', 'verbose_name_plural': '۳) کالاها'},
        ),
        migrations.AlterModelOptions(
            name='domesticcommoditytype',
            options={'verbose_name': 'نوع کالا', 'verbose_name_plural': '۲) انواع کالا'},
        ),
        migrations.AlterModelOptions(
            name='domesticdollarprice',
            options={'verbose_name': 'قیمت دلار', 'verbose_name_plural': '۷) قیمت\u200cهای دلار'},
        ),
        migrations.AlterModelOptions(
            name='domesticindustry',
            options={'verbose_name': 'صنعت', 'verbose_name_plural': '۱) صنایع'},
        ),
        migrations.AlterModelOptions(
            name='domesticmonthlysell',
            options={'verbose_name': 'فروش ماهانه', 'verbose_name_plural': '۶) فروش ماهانه'},
        ),
        migrations.AlterModelOptions(
            name='domesticproducer',
            options={'verbose_name': 'تولید کننده', 'verbose_name_plural': '۴) تولید کننده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='domestictrade',
            options={'verbose_name': 'معامله', 'verbose_name_plural': '۵) معاملات'},
        ),
        migrations.AlterModelOptions(
            name='domestictradeshistoryfetch',
            options={'verbose_name': 'تاریخچه دریافت اطلاعات بورس کالا', 'verbose_name_plural': '۹) تاریخچه دریافت اطلاعات بورس کالا'},
        ),
        migrations.AlterUniqueTogether(
            name='domesticmonthlysell',
            unique_together={('producer', 'commodity', 'commodity_name', 'start_date', 'end_date')},
        ),
    ]
