# Generated by Django 5.0.1 on 2024-08-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0027_alter_bourseviewcookie_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='domesticproducer',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_id'),
        ),
    ]
