# Generated by Django 5.0.1 on 2024-08-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0028_domesticproducer_unique_id'),
        ('stock_market', '0043_stockinstrument_stock_instrument_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domestic_producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='domestic_market.domesticproducer', verbose_name='تولید کننده بورس کالا')),
                ('stock_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domestic_relations', to='stock_market.stockinstrument', verbose_name='سهم')),
            ],
            options={
                'verbose_name': 'ارتباط',
                'verbose_name_plural': '۶) ارتباط\u200cها',
                'unique_together': {('domestic_producer', 'stock_instrument')},
            },
        ),
    ]
