# Generated by Django 5.0.1 on 2024-08-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0029_domesticrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domesticrelation',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': '۹) ارتباط\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='domestictradeshistoryfetch',
            options={'verbose_name': 'تاریخچه دریافت اطلاعات بورس کالا', 'verbose_name_plural': '۱۰) تاریخچه دریافت اطلاعات بورس کالا'},
        ),
    ]
