# Generated by Django 5.0.1 on 2024-08-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0030_alter_domesticrelation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bourseviewcookie',
            options={'verbose_name': 'کوکی', 'verbose_name_plural': '۰۸) کوکی'},
        ),
        migrations.AlterModelOptions(
            name='domesticcommodity',
            options={'verbose_name': 'کالا', 'verbose_name_plural': '۰۳) کالاها'},
        ),
    ]
