# Generated by Django 5.0.1 on 2024-08-05 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0031_alter_bourseviewcookie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domesticcommoditytype',
            options={'verbose_name': 'نوع کالا', 'verbose_name_plural': '۰۲) انواع کالا'},
        ),
        migrations.AlterModelOptions(
            name='domesticdollarprice',
            options={'verbose_name': 'قیمت دلار', 'verbose_name_plural': '۰۷) قیمت\u200cهای دلار'},
        ),
        migrations.AlterModelOptions(
            name='domesticindustry',
            options={'verbose_name': 'صنعت', 'verbose_name_plural': '۰۱) صنایع'},
        ),
        migrations.AlterModelOptions(
            name='domesticmonthlysell',
            options={'verbose_name': 'فروش ماهانه', 'verbose_name_plural': '۰۶) فروش ماهانه'},
        ),
        migrations.AlterModelOptions(
            name='domesticproducer',
            options={'verbose_name': 'تولید کننده', 'verbose_name_plural': '۰۴) تولید کننده\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='domestictrade',
            options={'verbose_name': 'معامله', 'verbose_name_plural': '۰۵) معاملات'},
        ),
    ]
