# Generated by Django 5.0.1 on 2024-08-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0032_alter_domesticcommoditytype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domesticrelation',
            options={'verbose_name': 'ارتباط', 'verbose_name_plural': '۰۹) ارتباط\u200cها'},
        ),
    ]
