# Generated by Django 5.0.1 on 2024-08-27 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0034_alter_domesticrelation_domestic_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domesticrelation',
            name='domestic_producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='domestic_market.domesticproducer', verbose_name='تولید کننده بورس کالا'),
        ),
    ]
