# Generated by Django 5.0.1 on 2024-09-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0035_alter_domesticrelation_domestic_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domestictrade',
            name='currency',
            field=models.CharField(default='ریال', max_length=255, verbose_name='ارز'),
        ),
    ]
