# Generated by Django 5.0.1 on 2024-09-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0036_alter_domestictrade_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domestictrade',
            name='currency',
            field=models.CharField(blank=True, default='ریال', max_length=255, null=True, verbose_name='ارز'),
        ),
    ]
