# Generated by Django 5.0.1 on 2025-03-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestic_market', '0037_alter_domestictrade_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestictrade',
            name='supply_pk',
            field=models.CharField(default='-', max_length=64, verbose_name='کد عرضه'),
        ),
    ]
