services:
  postgres_test:
    image: docker.arvancloud.ir/postgres:16
    container_name: postgres_test
    env_file:
      - .env.prod
    volumes:
      - postgres_test:/var/lib/postgresql/data
    networks:
      - test
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "24m"
        max-file: "10"

  redis_test:
    image: docker.arvancloud.ir/redis:7.2
    container_name: redis_test
    networks:
      - test
    depends_on:
      - postgres_test
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "24m"
        max-file: "10"

  mongodb_test:
    image: docker.arvancloud.ir/mongo:7.0.5
    container_name: mongodb_test
    volumes:
      - mongodb_test:/data/db
    networks:
      - test
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "24m"
        max-file: "10"

  api_test:
    mem_limit: 6g
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: dockerfile.api.prod
    image: api_test
    container_name: api_test
    entrypoint: ["/code/infra/entrypoints/api_test.sh"]
    volumes:
      - ticket_appendix:/code/media/tickets/
      - django_logs:/code/logs/
      - por_static:/code/static
    networks:
      - test
    depends_on:
      - postgres_test
      - redis_test
      - mongodb_test
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "24m"
        max-file: "10"

  worker_test:
    build:
      context: .
      dockerfile: dockerfile.api.prod
    image: worker_test
    container_name: worker_test
    env_file:
      - .env.prod
    entrypoint: ["/code/infra/entrypoints/worker_test.sh"]
    networks:
      - test
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "12m"
        max-file: "5"

  beat_test:
    build:
      context: .
      dockerfile: dockerfile.api.prod
    image: beat_test
    container_name: beat_test
    env_file:
      - .env.prod
    entrypoint: ["/code/infra/entrypoints/beat_test.sh"]
    networks:
      - test
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "12m"
        max-file: "5"

  flower_test:
    build:
      context: .
      dockerfile: dockerfile.api.prod
    image: flower_test
    container_name: flower_test
    env_file:
      - .env.prod
    entrypoint: ["/code/infra/entrypoints/flower_test.sh"]
    networks:
      - test
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "12m"
        max-file: "5"

networks:
  test:
    external: true
    driver: bridge
    name: test

volumes:
  postgres_test:
  mongodb_test:
  ticket_appendix:
  django_logs:
  por_static:
    name: por_static
