FROM docker.arvancloud.ir/python:3.12.3-slim

RUN ["apt", "update"]
RUN ["apt", "upgrade", "-y"]

RUN apt install -y --no-install-recommends \
build-essential \        
python3-dev \             
curl \                   
libxml2-dev \            
libxslt1-dev \           
libcairo2 \              
libcairo2-dev \          
freetype2-demos \        
libfreetype6-dev \       
libgdk-pixbuf2.0-dev \   
gettext \                
libjpeg-dev \            
liblcms2-dev \           
libffi-dev \             
libopenjp2-7-dev \       
libssl-dev \             
libpango1.0-dev \        
poppler-utils \          
postgresql-client \      
libpq-dev \              
python3-cffi \           
cargo \                  
rustc \                  
tcl-dev \                
libtiff-dev \            
tk-dev \                 
zlib1g-dev               


WORKDIR /code

RUN ["pip", "install", "--upgrade", "pip", "setuptools", "wheel"]
RUN ["pip", "install", "pdm"]
RUN ["pdm", "self", "update"]
COPY ./pdm.lock /code/
COPY ./pyproject.toml /code/
RUN pdm export -o requirements.txt
# RUN ["pip", "install", "-r", "/code/requirements.txt", "-i" , "https://mirror-pypi.runflare.com/simple/"]
RUN ["pip", "install", "-r", "/code/requirements.txt"]
RUN ["playwright", "install"]
RUN ["playwright", "install-deps"]

COPY . /code/

RUN ["mkdir", "-p", "logs"]

RUN ["chmod", "+x", "./infra/entrypoints/api_test.sh"]
RUN ["chmod", "+x", "./infra/entrypoints/apscheduler_test.sh"]

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV DJANGO_SETTINGS_MODULE=samaneh.settings

ENV REDIS_SERVICE_NAME=redis_test
ENV MONGODB_SERVICE_NAME=mongodb_test
ENV POSTGRES_SERVICE_NAME=postgres_test

ENV EMAIL_HOST=smtp.gmail.com
ENV EMAIL_PORT=587
ENV EMAIL_HOST_USER=armansmtptest@gmail.com
ENV EMAIL_TO=saraey.gholamreza@gmail.com

ENV DEBUG=True

ENV ADMIN_USERNAME=admin
ENV ADMIN_FIRST_NAME=ادمین

ENV SERVER_NAME=LOCAL
