services:
  postgres_test:
    mem_limit: 1g
    image: docker.arvancloud.ir/postgres:16
    container_name: postgres_test
    environment:
      POSTGRES_DB: samane_jame_test
      POSTGRES_USER: arman
      POSTGRES_PASSWORD: arman
    volumes:
      - postgres_test:/var/lib/postgresql/data
    networks:
      - test
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "24m"
        max-file: "10"
  redis_test:
    mem_limit: 512m
    image: docker.arvancloud.ir/redis:7.2
    container_name: redis_test
    networks:
      - test
    depends_on:
      - postgres_test
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "24m"
        max-file: "10"
  mongodb_test:
    mem_limit: 2g
    container_name: mongodb_test
    image: docker.arvancloud.ir/mongo:7.0.5
    volumes:
      - mongodb_test:/data/db
    networks:
      - test
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "24m"
        max-file: "10"
  api_test:
    mem_limit: 3g
    build:
      context: .
      dockerfile: Dockerfile.api.test
    image: api_test
    container_name: api_test
    entrypoint: ["/code/infra/entrypoints/api_test.sh"]
    volumes:
      - shared_options_excel_files_test:/code/media/uploaded_files/
      - ticket_appendix:/code/media/tickets/
      - django_logs:/code/logs/
    networks:
      - test
    depends_on:
      - postgres_test
      - redis_test
      - mongodb_test
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "24m"
        max-file: "10"
  worker_test:
    mem_limit: 512m
    build:
      context: .
      dockerfile: Dockerfile.api.test
    image: worker_test
    container_name: worker_test
    entrypoint: ["/code/infra/entrypoints/worker_test.sh"]
    volumes:
      - shared_options_excel_files_test:/code/media/uploaded_files/
      - ticket_appendix:/code/media/tickets/
    networks:
      - test
    depends_on:
      - postgres_test
      - redis_test
      - mongodb_test
      - api_test
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "24m"
        max-file: "10"
  beat_test:
    mem_limit: 512m
    build:
      context: .
      dockerfile: Dockerfile.api.test
    image: beat_test
    container_name: beat_test
    entrypoint: ["/code/infra/entrypoints/beat_test.sh"]
    volumes:
      - shared_options_excel_files_test:/code/media/uploaded_files/
      - ticket_appendix:/code/media/tickets/
    networks:
      - test
    depends_on:
      - postgres_test
      - redis_test
      - mongodb_test
      - api_test
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "24m"
        max-file: "10"
  nginx:
    mem_limit: 512m
    build:
      context: .
      dockerfile: Dockerfile.nginx.test
    image: nginx_test
    container_name: nginx_test
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api_test
    networks:
      - test
    volumes:
      - nginx_logs:/var/log/nginx/

networks:
  test:
    external: true
    driver: bridge
    name: test

volumes:
  postgres_test:
  mongodb_test:
  shared_options_excel_files_test:
  ticket_appendix:
  django_logs:
  nginx_logs:
