# GET BASE IMAGE
FROM docker.arvancloud.ir/python:3.12.3-alpine3.20

# INSTALL REQUIRED PACKAGES ON ALPINE
RUN echo "https://mirrors.gigenet.com/alpinelinux/v3.20/main/" > /etc/apk/repositories && \
echo "https://mirrors.gigenet.com/alpinelinux/v3.20/community/" >> /etc/apk/repositories
RUN ["apk", "update"]
RUN apk add \
  gcc \
  python3-dev \
  musl-dev \
  linux-headers \
  curl \
  libxml2-dev \
  libxslt-dev \
  build-base \
  cairo \
  cairo-dev \
  cargo \
  freetype-dev \
  gcc \
  gdk-pixbuf-dev \
  gettext \
  jpeg-dev \
  lcms2-dev \
  libffi-dev \
  openjpeg-dev \
  openssl-dev \
  pango-dev \
  poppler-utils \
  postgresql-client \
  postgresql-dev \
  py-cffi \
  python3-dev \
  rust \
  tcl-dev \
  tiff-dev \
  tk-dev \
  zlib-dev \
  build-base

WORKDIR /code

# INSTALL PDM AND DEPENDENCIES
RUN ["pip", "install", "--upgrade", "pip", "setuptools", "wheel"]
RUN ["pip", "install", "pdm"]
RUN ["pdm", "self", "update"]
COPY ./pdm.lock /code/
COPY ./pyproject.toml /code/
RUN pdm export -o requirements.txt
# RUN ["pip", "install", "-r", "/code/requirements.txt", "-i" , "https://mirror-pypi.runflare.com/simple/"]
RUN ["pip", "install", "-r", "/code/requirements.txt"]

# COPY SOURCE CODE INTO DOCKER IMAGE
COPY . /code/

RUN ["mkdir", "-p", "logs"]

# GRANT EXCUTE PERMISSSION TO ENTRYPOINTS FILES
RUN ["chmod", "+x", "./infra/entrypoints/api_test.sh"]
RUN ["chmod", "+x", "./infra/entrypoints/apscheduler_test.sh"]

# PYTHON CONFIGS
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# DJANGO CONFIGS
ENV DJANGO_SETTINGS_MODULE=samaneh.settings.test
ENV SECRET_KEY="django-insecure-oi-e(9+%x^#hj-x4y32+!(auwgtj513eccl%dg+!&ldf36uk8-"

# MONGODB & REDIS SERVICE NAMES
ENV REDIS_SERVICE_NAME=redis_test
ENV MONGODB_SERVICE_NAME=mongodb_test

# SMTP EMAIL CONFIGS
ENV EMAIL_HOST=smtp.gmail.com
ENV EMAIL_PORT=587
ENV EMAIL_HOST_USER=armansmtptest@gmail.com
ENV EMAIL_HOST_PASSWORD="gaux sxiy zhyf qhdx"
ENV EMAIL_TO=saraey.gholamreza@gmail.com

ENV MELIPAYAMAK_USERNAME=09102188113
ENV MELIPAYAMAK_PASSOWRD=TL5OC

ENV DEBUG=False

ENV POSTGRES_DB=samane_jame_test
ENV POSTGRES_USER=arman
ENV POSTGRES_PASSWORD=arman
ENV POSTGRES_SERVICE_NAME=postgres_test

ENV ZARINPAL_MERCHANTID=8a4c30e4-a37a-4151-9d00-affbf3d4b79c
ENV ZARINPAL_VERIFY_TRANSACTION_CALLBACKURL=/api/payment/zarinpal/
ENV ZP_PAY_REQUEST_URL=https://www.zarinpal.com/pg/rest/WebGate/PaymentRequest.json
ENV ZP_STARTPAY_URL=https://www.zarinpal.com/pg/StartPay/
ENV ZP_REDIRECT_FRONTEND_URL=/dashboard/recommended/recommended
ENV ZP_PAY_VERIFY_URL=https://www.zarinpal.com/pg/rest/WebGate/PaymentVerification.json
