# GET BASE IMAGE
FROM docker.arvancloud.ir/nginx:1.27.2-alpine3.20

# INSTALL REQUIRED PACKAGES ON ALPINE
RUN echo "https://mirrors.gigenet.com/alpinelinux/v3.20/main/" > /etc/apk/repositories && \
    echo "https://mirrors.gigenet.com/alpinelinux/v3.20/community/" >> /etc/apk/repositories
RUN ["apk", "update"]
RUN ["apk", "upgrade", "-U", "-a"]

COPY ./infra/nginx/ /etc/nginx/
COPY ./infra/nginx/updating.html /
COPY ./static/ /etc/nginx/static/
COPY ./option_market/strategy-schema/ /etc/nginx/strategy-schema/

RUN chmod -R 755 /etc/nginx/static/
RUN chown -R root:root /etc/nginx/static/

RUN chmod -R 755 /etc/nginx/strategy-schema/
RUN chown -R root:root /etc/nginx/strategy-schema/
