# Generated by Django 5.0.1 on 2024-10-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEquity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_equity_key', models.CharField(choices=[('updateSandoqMarketsInfo', 'صندوق\u200cهای کالایی (updateSandoqMarketsInfo)'), ('updateGavahiMarketsInfo', 'گواهی سپرده کالایی - غیر شمش و سکه طلا (updateGavahiMarketsInfo)'), ('updateCDCMarketsInfo', 'شمش و سکه طلا (updateCDCMarketsInfo)')], max_length=100, verbose_name='دسته\u200cبندی')),
                ('base_equity_name', models.CharField(max_length=255, verbose_name='نام دارایی پایه')),
                ('base_equity_col', models.CharField(choices=[('ID', 'ID'), ('ContractCode', 'ContractCode')], max_length=100, verbose_name='نام ستون یکتا')),
                ('base_equity_value', models.CharField(max_length=100, verbose_name='مقدار ستون یکتا')),
            ],
            options={
                'verbose_name': 'دارایی پایه',
                'verbose_name_plural': '۱) دارایی\u200cهای پایه',
            },
        ),
        migrations.CreateModel(
            name='Derivative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('derivative_key', models.CharField(choices=[('updateFutureMarketsInfo', 'آتی (updateFutureMarketsInfo)'), ('updateMarketsInfo', 'اختیار معامله (updateMarketsInfo)')], max_length=100, verbose_name='قرارداد مشتقه')),
                ('derivative_name', models.CharField(max_length=255, verbose_name='نام قرارداد')),
                ('derivative_col', models.CharField(choices=[('ContractCode', 'ContractCode'), ('CallContractID', 'CallContractID'), ('PutContractID', 'PutContractID')], max_length=100, verbose_name='نام ستون یکتای قرارداد مشتقه')),
                ('derivative_value', models.CharField(max_length=100, verbose_name='مقدار ستون یکتا')),
                ('base_equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivatives', to='future_market.baseequity', verbose_name='دارایی پایه')),
            ],
            options={
                'verbose_name': 'قرارداد مشتقه',
                'verbose_name_plural': '۲) قراردادهای مشتقه',
            },
        ),
    ]
