# Generated by Django 5.0.1 on 2024-10-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Derivative',
        ),
    ]
