# Generated by Django 5.0.1 on 2024-10-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_market', '0002_delete_derivative'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseEquity',
            new_name='BaseEquityOld',
        ),
    ]
