# Generated by Django 5.0.1 on 2024-10-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_market', '0003_rename_baseequity_baseequityold'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEquity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_equity_key', models.CharField(choices=[('updateSandoqMarketsInfo', 'صندوق\u200cهای کالایی (updateSandoqMarketsInfo)'), ('updateGavahiMarketsInfo', 'گواهی سپرده کالایی - غیر شمش و سکه طلا (updateGavahiMarketsInfo)'), ('updateCDCMarketsInfo', 'شمش و سکه طلا (updateCDCMarketsInfo)')], max_length=100, verbose_name='دسته\u200cبندی')),
                ('base_equity_name', models.CharField(max_length=255, verbose_name='نام دارایی پایه')),
                ('derivative_symbol', models.CharField(max_length=100, verbose_name='نماد قرارداد مشتقه')),
            ],
            options={
                'verbose_name': 'دارایی پایه',
                'verbose_name_plural': '۱) دارایی\u200cهای پایه',
            },
        ),
        migrations.AlterModelOptions(
            name='baseequityold',
            options={'verbose_name': 'old دارایی پایه', 'verbose_name_plural': '۱) old دارایی\u200cهای پایه'},
        ),
    ]
