# Generated by Django 5.0.1 on 2024-10-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_market', '0004_baseequity_alter_baseequityold_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseEquityOld',
        ),
    ]
