# Generated by Django 5.0.1 on 2024-10-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_market', '0005_delete_baseequityold'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseequity',
            name='unique_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه'),
        ),
    ]
