# Generated by Django 5.0.1 on 2025-01-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_market', '0006_baseequity_unique_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseequity',
            options={'verbose_name': 'دارایی پایه آتی', 'verbose_name_plural': '۱) (آتی) دارایی\u200cهای پایه'},
        ),
    ]
