# Generated by Django 5.0.1 on 2025-01-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_market', '0007_alter_baseequity_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseEquity',
            new_name='FutureBaseEquity',
        ),
    ]
