# Generated by Django 5.0.1 on 2025-01-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_market', '0008_rename_baseequity_futurebaseequity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionBaseEquity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_equity_key', models.CharField(choices=[('updateSandoqMarketsInfo', 'صندوق\u200cهای کالایی (updateSandoqMarketsInfo)'), ('updateGavahiMarketsInfo', 'گواهی سپرده کالایی - غیر شمش و سکه طلا (updateGavahiMarketsInfo)'), ('updateCDCMarketsInfo', 'شمش و سکه طلا (updateCDCMarketsInfo)')], max_length=64, verbose_name='دسته\u200cبندی')),
                ('base_equity_name', models.CharField(max_length=128, verbose_name='نام دارایی پایه')),
                ('derivative_symbol', models.CharField(max_length=32, verbose_name='نماد قرارداد مشتقه')),
                ('unique_identifier', models.CharField(blank=True, max_length=128, null=True, verbose_name='شناسه')),
            ],
            options={
                'verbose_name': 'دارایی پایه آپشن',
                'verbose_name_plural': '۱) (آپشن) دارایی\u200cهای پایه',
            },
        ),
    ]
