# Generated by Django 5.0.1 on 2024-06-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام ویژگی')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_enable', models.BooleanField(blank=True, null=True, verbose_name='وضعیت')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار ویژگی')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
