# Generated by Django 5.0.1 on 2024-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuretoggle',
            name='is_enable',
        ),
        migrations.AddField(
            model_name='featuretoggle',
            name='state',
            field=models.IntegerField(choices=[(1, 'فعال'), (2, 'غیرفعال')], default=1, verbose_name='وضعیت'),
            preserve_default=False,
        ),
    ]
