# Generated by Django 5.0.1 on 2024-12-10 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_id', models.CharField(max_length=64, verbose_name='شناسه تراکنش')),
                ('plan', models.CharField(default='feat: ..., dur: ..., pr: ..., dis_per: ..., dis_pr: ...', max_length=255, verbose_name='طرح')),
                ('discount', models.CharField(default='type: ..., name: ..., dis_per: ..., code: ... | ..., st: ..., ex: ..., use: ... | ... | ...', max_length=255, verbose_name='تخفیف')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('method', models.CharField(choices=[('zarinpal', 'زرین\u200cپال')], max_length=16, verbose_name='روش پرداخت')),
                ('pay_id', models.CharField(max_length=128, verbose_name='شناسه پرداخت')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('tracking_id', models.CharField(max_length=128, verbose_name='کد رهگیری')),
                ('description', models.CharField(max_length=128, verbose_name='توضیحات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش\u200c',
                'verbose_name_plural': '۱) تراکنش\u200cها',
            },
        ),
    ]
