# Generated by Django 5.0.1 on 2024-12-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='TX Created', max_length=128, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount',
            field=models.CharField(default='tp: ..., name: ..., dis_per: ..., code: ... | ..., st: ..., ex: ..., use: ... | ... | ...', max_length=255, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pay_id',
            field=models.CharField(default='', max_length=128, verbose_name='شناسه پرداخت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.CharField(default='feat: ..., dur: ..., login: ..., pr: ..., dis_per: ..., dis_pr: ...', max_length=255, verbose_name='طرح'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tracking_id',
            field=models.CharField(default='', max_length=128, verbose_name='کد رهگیری'),
        ),
    ]
