# Generated by Django 5.0.1 on 2024-12-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال')], default='zarinpal', max_length=16, verbose_name='روش پرداخت'),
        ),
    ]
