# Generated by Django 5.0.1 on 2024-12-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transaction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='tx-created', max_length=128, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount',
            field=models.CharField(default=dict, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.JSONField(default=dict, verbose_name='طرح'),
        ),
    ]
