# Generated by Django 5.0.1 on 2024-12-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='discount',
            field=models.JSONField(default=dict, verbose_name='تخفیف'),
        ),
    ]
