# Generated by Django 5.0.1 on 2024-12-15 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_feature_is_enabled_subscription_is_enabled'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0005_alter_transaction_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش\u200c', 'verbose_name_plural': '۲) تراکنش\u200cها'},
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_id', models.PositiveIntegerField()),
                ('tx_id', models.CharField(max_length=64, verbose_name='شناسه تراکنش')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('method', models.CharField(choices=[('zarinpal', 'زرین\u200cپال')], default='zarinpal', max_length=16, verbose_name='روش پرداخت')),
                ('pay_id', models.CharField(default='', max_length=128, verbose_name='شناسه پرداخت')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('tracking_id', models.CharField(default='', max_length=128, verbose_name='کد رهگیری')),
                ('description', models.CharField(default='tx-created', max_length=128, verbose_name='توضیحات')),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='contenttypes.contenttype', verbose_name='تخفیف')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='account.feature', verbose_name='طرح')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رسید تراکنش\u200c',
                'verbose_name_plural': '۱) رسید تراکنش\u200cها',
            },
        ),
    ]
