# Generated by Django 5.0.1 on 2024-12-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0006_alter_transaction_options_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='discount_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='آیدی تخفیف'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='discount_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='contenttypes.contenttype', verbose_name='تخفیف'),
        ),
    ]
