# Generated by Django 5.0.1 on 2024-12-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_receipt_discount_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='tx_id',
            new_name='receipt_id',
        ),
    ]
