# Generated by Django 5.0.1 on 2024-12-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_tx_id_receipt_receipt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.CharField(default='receipt-created', max_length=128, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='receipt-created', max_length=128, verbose_name='توضیحات'),
        ),
    ]
