# Generated by Django 5.0.1 on 2024-12-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_receipt_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='method',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال')], default='', max_length=16, verbose_name='روش پرداخت'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
