# Generated by Django 5.0.1 on 2025-03-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_receipt_method_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedReceipt',
            fields=[
            ],
            options={
                'verbose_name': 'رسید تراکنش\u200c',
                'verbose_name_plural': '۱) رسید تراکنش\u200cها (تایید شده)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.receipt',),
        ),
        migrations.CreateModel(
            name='NotConfirmedReceipt',
            fields=[
            ],
            options={
                'verbose_name': 'رسید تراکنش\u200c',
                'verbose_name_plural': '۱) رسید تراکنش\u200cها (تایید نشده)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.receipt',),
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'رسید تراکنش\u200c', 'verbose_name_plural': '۱) رسید تراکنش\u200cها (همه)'},
        ),
    ]
