# Generated by Django 5.0.1 on 2025-03-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_confirmedreceipt_notconfirmedreceipt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmedreceipt',
            options={'verbose_name': 'رسید تراکنش\u200c', 'verbose_name_plural': '۳) رسید تراکنش\u200cها (تایید شده)'},
        ),
        migrations.AlterModelOptions(
            name='notconfirmedreceipt',
            options={'verbose_name': 'رسید تراکنش\u200c', 'verbose_name_plural': '۲) رسید تراکنش\u200cها (تایید نشده)'},
        ),
    ]
