# Generated by Django 5.0.1 on 2024-07-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام استراتژی')),
                ('collection_key', models.CharField(max_length=255, verbose_name='نام کلید')),
            ],
            options={
                'verbose_name': 'استراتژی',
                'verbose_name_plural': 'استراتژی\u200cها',
            },
        ),
    ]
