# Generated by Django 5.0.1 on 2024-08-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام استراتژی')),
                ('key', models.CharField(max_length=255, verbose_name='نام کلید')),
            ],
            options={
                'verbose_name': 'استراتژی',
                'verbose_name_plural': 'استراتژی\u200cها',
            },
        ),
    ]
