# Generated by Django 5.0.1 on 2024-08-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0002_optionstrategy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'استراتژی (قدیم)', 'verbose_name_plural': 'استراتژی\u200cها (قدیم)'},
        ),
    ]
