# Generated by Django 5.0.1 on 2024-08-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0003_alter_strategy_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='strategy',
            constraint=models.UniqueConstraint(fields=('id',), name='strategy_unique_id'),
        ),
    ]
