# Generated by Django 5.0.1 on 2024-08-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0004_strategy_strategy_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrategy',
            name='category',
            field=models.CharField(choices=[('no_risk', 'استراتژی\u200cهای بدون ریسک'), ('low_risk', 'استراتژی\u200cهای با ریسک کم'), ('mid_risk', 'استراتژی\u200cهای با ریسک متوسط'), ('high_risk', 'استراتژی\u200cهای با ریسک زیاد')], default='no_risk', max_length=255, verbose_name='نوع'),
        ),
    ]
