# Generated by Django 5.0.1 on 2024-08-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0005_optionstrategy_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstrategy',
            name='key',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام کلید'),
        ),
    ]
