# Generated by Django 5.0.1 on 2024-08-28 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0006_alter_optionstrategy_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='optionstrategy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionstrategy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
