# Generated by Django 5.0.1 on 2024-08-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0007_risklevel_optionstrategy_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionstrategy',
            options={'verbose_name': 'استراتژی', 'verbose_name_plural': '۰۱) استراتژی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='risklevel',
            options={'verbose_name': 'سطح ریسک', 'verbose_name_plural': '۰۲) سطوح ریسک'},
        ),
        migrations.AddField(
            model_name='risklevel',
            name='level',
            field=models.CharField(choices=[('no_risk', 'استراتژی\u200cهای بدون ریسک'), ('low_risk', 'استراتژی\u200cهای با ریسک کم'), ('high_risk', 'استراتژی\u200cهای با ریسک زیاد')], default='no_risk', max_length=255, verbose_name='سطح ریسک'),
        ),
        migrations.AddField(
            model_name='risklevel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='risklevel',
            name='option_strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_level', to='option_market.optionstrategy'),
        ),
    ]
