# Generated by Django 5.0.1 on 2024-08-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0008_alter_optionstrategy_options_alter_risklevel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionstrategy',
            name='category',
        ),
    ]
