# Generated by Django 5.0.1 on 2024-08-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0010_risklevel_profit_status_alter_risklevel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risklevel',
            name='level',
            field=models.CharField(choices=[('no_risk', 'استراتژی\u200cهای بدون ریسک'), ('low_risk', 'استراتژی\u200cهای با ریسک کم'), ('high_risk', 'استراتژی\u200cهای با ریسک زیاد'), ('lower_risk', 'کاهنده ریسک'), ('higher_risk_roi', 'افزایش ریسک و بازدهی')], default='no_risk', max_length=255, verbose_name='سطح ریسک'),
        ),
        migrations.AlterField(
            model_name='risklevel',
            name='profit_status',
            field=models.CharField(choices=[('limited_profit', 'با سود محدود'), ('unlimited_profit', 'با سود نامحدود')], default='limited_profit', max_length=255, verbose_name='وضعیت سوددهی'),
        ),
    ]
