# Generated by Django 5.0.1 on 2024-09-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0011_alter_risklevel_level_alter_risklevel_profit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risklevel',
            name='level',
            field=models.CharField(choices=[('no_risk', 'استراتژی\u200cهای بدون ریسک'), ('low_risk', 'استراتژی\u200cهای با ریسک کم'), ('high_risk', 'استراتژی\u200cهای با ریسک زیاد'), ('lower_risk', 'استراتژی\u200cهای کاهنده ریسک'), ('higher_risk_roi', 'استراتژی\u200cهای افزایش ریسک و بازدهی')], default='no_risk', max_length=255, verbose_name='سطح ریسک'),
        ),
    ]
