# Generated by Django 5.0.1 on 2024-09-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0012_alter_risklevel_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='نام استراتژی')),
                ('key', models.CharField(max_length=255, verbose_name='نام کلید')),
                ('profit_status', models.CharField(choices=[('limited_profit', 'با سود محدود'), ('unlimited_profit', 'با سود نامحدود')], default='limited_profit', max_length=255, verbose_name='وضعیت سوددهی')),
                ('risk_level', models.CharField(choices=[('no_risk', 'استراتژی\u200cهای بدون ریسک'), ('low_risk', 'استراتژی\u200cهای با ریسک کم'), ('high_risk', 'استراتژی\u200cهای با ریسک زیاد')], default='no_risk', max_length=255, verbose_name='سطح ریسک')),
            ],
            options={
                'verbose_name': 'استراتژی',
                'verbose_name_plural': '۰۱) استراتژی\u200cها (جدید)',
            },
        ),
    ]
