# Generated by Django 5.0.1 on 2024-09-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0013_strategyoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionstrategy',
            options={'verbose_name': 'استراتژی', 'verbose_name_plural': '۰۰) استراتژی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='risklevel',
            options={'verbose_name': 'سطح ریسک', 'verbose_name_plural': '۰۰) سطوح ریسک'},
        ),
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'استراتژی (قدیم)', 'verbose_name_plural': '۰۰) استراتژی\u200cها (قدیم)'},
        ),
    ]
