# Generated by Django 5.0.1 on 2024-09-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0014_alter_optionstrategy_options_alter_risklevel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyoption',
            name='profit_status',
            field=models.CharField(choices=[('all_profit', 'همه'), ('limited_profit', 'با سود محدود'), ('unlimited_profit', 'با سود نامحدود')], default='limited_profit', max_length=255, verbose_name='وضعیت سوددهی'),
        ),
        migrations.AlterField(
            model_name='strategyoption',
            name='risk_level',
            field=models.CharField(choices=[('all_risk', 'همه'), ('no_risk', 'استراتژی\u200cهای بدون ریسک'), ('low_risk', 'استراتژی\u200cهای با ریسک کم'), ('high_risk', 'استراتژی\u200cهای با ریسک زیاد')], default='no_risk', max_length=255, verbose_name='سطح ریسک'),
        ),
    ]
