# Generated by Django 5.0.1 on 2024-09-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0015_alter_strategyoption_profit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyoption',
            name='profit_status',
            field=models.CharField(choices=[('limited_profit', 'با سود محدود'), ('unlimited_profit', 'با سود نامحدود')], default='limited_profit', max_length=255, verbose_name='وضعیت سوددهی'),
        ),
        migrations.AlterField(
            model_name='strategyoption',
            name='risk_level',
            field=models.CharField(choices=[('no_risk', 'استراتژی\u200cهای بدون ریسک'), ('low_risk', 'استراتژی\u200cهای با ریسک کم'), ('high_risk', 'استراتژی\u200cهای با ریسک زیاد')], default='no_risk', max_length=255, verbose_name='سطح ریسک'),
        ),
    ]
