# Generated by Django 5.0.1 on 2024-09-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0016_alter_strategyoption_profit_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risklevel',
            name='option_strategy',
        ),
        migrations.DeleteModel(
            name='OptionStrategy',
        ),
        migrations.DeleteModel(
            name='RiskLevel',
        ),
    ]
