# Generated by Django 5.0.1 on 2024-09-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0017_remove_risklevel_option_strategy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
