# Generated by Django 5.0.1 on 2024-10-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0018_delete_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyoption',
            name='sequence',
            field=models.IntegerField(default=1, verbose_name='ترتیب'),
        ),
    ]
