# Generated by Django 5.0.1 on 2024-11-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0019_strategyoption_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategyoption',
            options={'verbose_name': 'استراتژی', 'verbose_name_plural': '۰۱) استراتژی\u200cها'},
        ),
    ]
