# Generated by Django 5.0.1 on 2024-12-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0020_alter_strategyoption_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyoption',
            name='desc',
            field=models.CharField(default='-', max_length=128, verbose_name='نحوه اجرای استراتژی'),
        ),
        migrations.AlterField(
            model_name='strategyoption',
            name='profit_status',
            field=models.CharField(choices=[('limited_profit', 'سود محدود'), ('unlimited_profit', 'سود نامحدود')], default='limited_profit', max_length=255, verbose_name='وضعیت سوددهی'),
        ),
    ]
