# Generated by Django 5.0.1 on 2024-12-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0021_strategyoption_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyoption',
            name='desc',
            field=models.CharField(default='-', max_length=255, verbose_name='نحوه اجرای استراتژی'),
        ),
    ]
