# Generated by Django 5.0.1 on 2025-03-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0022_alter_strategyoption_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('call_value', models.IntegerField(verbose_name='ارزش کال (میلیارد تومان)')),
                ('put_value', models.IntegerField(verbose_name='ارزش پوت (میلیارد تومان)')),
                ('option_value', models.IntegerField(verbose_name='ارزش آپشن (میلیارد تومان)')),
                ('call_to_put', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='نسبت کال به پوت')),
                ('option_to_market', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='نسبت آپشن به بازار')),
            ],
            options={
                'verbose_name': 'تاریخچه ارزش آپشن\u200cها',
                'verbose_name_plural': '۰۲) تاریخچه ارزش آپشن\u200cها',
            },
        ),
    ]
