# Generated by Django 5.0.1 on 2025-03-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0024_alter_optionvalue_call_to_put'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='call_to_put',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='نسبت کال به پوت'),
        ),
    ]
