# Generated by Django 5.0.1 on 2025-03-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0025_alter_optionvalue_call_to_put'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='call_value',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='ارزش کال (میلیارد تومان)'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='option_to_market',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='نسبت آپشن به بازار'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='option_value',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='ارزش آپشن (میلیارد تومان)'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='put_value',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='ارزش پوت (میلیارد تومان)'),
        ),
    ]
