# Generated by Django 5.0.1 on 2025-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0026_alter_optionvalue_call_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='option_to_market',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='نسبت آپشن به بازار'),
        ),
    ]
