# Generated by Django 5.0.1 on 2025-03-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0027_alter_optionvalue_option_to_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='call_value',
            field=models.IntegerField(verbose_name='ارزش کال (میلیارد تومان)'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='option_value',
            field=models.IntegerField(verbose_name='ارزش آپشن (میلیارد تومان)'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='put_value',
            field=models.IntegerField(verbose_name='ارزش پوت (میلیارد تومان)'),
        ),
    ]
