# Generated by Django 5.0.1 on 2025-03-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0028_alter_optionvalue_call_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='call_value',
            field=models.IntegerField(verbose_name='ارزش کال (میلیون تومان)'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='option_value',
            field=models.IntegerField(verbose_name='ارزش آپشن (میلیون تومان)'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='put_value',
            field=models.IntegerField(verbose_name='ارزش پوت (میلیون تومان)'),
        ),
    ]
