# Generated by Django 5.0.1 on 2025-03-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0029_alter_optionvalue_call_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionvalue',
            name='call_to_put',
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='put_to_call',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='نسبت پوت به کال'),
            preserve_default=False,
        ),
    ]
