# Generated by Django 5.0.1 on 2025-03-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0030_remove_optionvalue_call_to_put_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='put_to_call',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='نسبت پوت به کال'),
        ),
    ]
