# Generated by Django 5.0.1 on 2025-03-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_market', '0031_alter_optionvalue_put_to_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='call_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='ارزش کال (میلیون تومان)'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='option_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='ارزش آپشن (میلیون تومان)'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='put_value',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='ارزش پوت (میلیون تومان)'),
        ),
    ]
