import os
from pytz import timezone

######################################################## CACHE
SIXTY_SECONDS_CACHE = 60  # 60 seconds
FIVE_MINUTES_CACHE = 60 * 5  # 5 minutes
THIRTY_MINUTES_CACHE = 60 * 30  # 30 minutes
SIXTY_MINUTES_CACHE = 60 * 60  # 60 minutes
SIX_HOURS_CACHE = 60 * 60 * 6  # 6 hours


######################################################## REDIS_DBs
KEY_WITH_EX_REDIS_DB = 1  # CORE
OPTION_REDIS_DB = 3  # FUTURE
FUTURE_REDIS_DB = 4  # FUTURE
STOCK_REDIS_DB = 5  # STOCK
USER_AGENTS_REDIS_DB = 13  # CORE
ONLINE_USERS_REDIS_DB = 15  # CORE


######################################################## CORE APP
DASHBOARD_MONGO_DB = "dashboard"
BUY_SELL_ORDERS_COLLECTION = "buy_sell_orders"
LAST_CLOSE_PRICE_COLLECTION = "last_close_price"
AUTO_MODE = "auto"
MANUAL_MODE = "manual"
MGT_FOR_DAILY_TASKS = 50 * 60  # 50 Minutes


######################################################## ACCOUNT APP
REDIS_SIGNUP_PREFIX = "username_verify_code_"
REDIS_EMAIL_VERIFY_PREFIX = "email_verify_code_"
REDIS_RESET_PASSWORD_PREFIX = "reset_password_code_"
MELIPAYAMAK_OK_RESPONSE = "Ok"
SIGNUP_CODE_EXPIRY = 60 * 5  # 5 Minutes
RESET_PASSWORD_CODE_EXPIRY = SIGNUP_CODE_EXPIRY
EMAIL_VERIFY_CODE_EXPIRY = 60 * 5  # 5 Minutes
SIGNUP_TRY_COUNT_EXPIRY = 60 * 60 * 24  # 24 Hours
CODE_RANGE_MIN = 111111
CODE_RANGE_MAX = 999999
PHONE_PATTERN = r"^09(0[0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9]|6[0-9]|7[0-9]|8[0-9]|9[0-9])-?[0-9]{3}-?[0-9]{4}$"


######################################################## DOMESTIC APP
DOMESTIC_MONGO_DB = "domestic"


######################################################## GLOBAL APP
GLOBAL_MONGO_DB = "global"


######################################################## OPTIONS APP
OPTION_MONGO_DB = "option"
OPTION_TRADE_FEE = 0.00103
OPTION_LIQUIDATION_SETTLEMENT_FEE = 0.0005
OPTION_PHYSICAL_SETTLEMENT_FEE = 0.0005
BASE_EQUITY_BUY_FEE = 0.003712
BASE_EQUITY_SELL_FEE = 0.0088

######################################################## STOCK APP
MARKET_WATCH_REDIS_KEY = "market_watch"
STOCK_MONGO_DB = "stock"
STOCK_NA_ROI = -1000
MARKET_WATCH_TOP_5_LIMIT = 5
STOCK_TOP_500_LIMIT = 500
STOCK_TOP_100_LIMIT = 100
STOCK_NO_ROI_LETTER = "ناموجود"
NO_DAILY_HISTORY = "NDH"
NO_HISTORY_DATE = "NHD"
STOCK_VALUE_CHANGE_DURATION = 30  # DAYS
STOCK_OPTION_STRIKE_DEVIATION = 5  # PERCENT

######################################################## COMMON
# DOMESTIC & GLOBAL MEAN DEVIATION
COMMODITY_TOP_200_LIMIT = 200
TEHRAN_TZ = timezone("Asia/Tehran")

# UNIT CONVERSION
HEZAR_RIAL_TO_MILLION_TOMAN = 10_000
HEZAR_RIAL_TO_BILLION_TOMAN = 10_000_000
RIAL_TO_BILLION_TOMAN = 10_000_000_000
RIAL_TO_MILLION_TOMAN = 10_000_000
TO_MILLION = 1_000_000

# PERSIAN TO ENGLISH NUMBER CONVERTER
PERSIAN_DIGITS = "۱۲۳۴۵۶۷۸۹۰١٢٣٤٥٦٧٨٩٠"
ENGLISH_DIGITS = "12345678901234567890"
FA_TO_EN_TRANSLATION_TABLE = str.maketrans(PERSIAN_DIGITS, ENGLISH_DIGITS)

# EMAIL
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = os.environ.get("EMAIL_PORT")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_TO = os.environ.get("EMAIL_TO")

# SMS
PORTFOYAR_SMS_ID = 263013
MELIPAYAMAK_USERNAME = os.environ.get("MELIPAYAMAK_USERNAME")
MELIPAYAMAK_PASSOWRD = os.environ.get("MELIPAYAMAK_PASSOWRD")

# ZARINPAL PAYMENT METHOD CONFIGURATIONS
ZARINPAL_MERCHANTID = os.environ.get("ZARINPAL_MERCHANTID")
ZARINPAL_VERIFY_TRANSACTION_CALLBACKURL = os.environ.get(
    "ZARINPAL_VERIFY_TRANSACTION_CALLBACKURL"
)
ZP_PAY_REQUEST_URL = os.environ.get("ZP_PAY_REQUEST_URL")
ZP_STARTPAY_URL = os.environ.get("ZP_STARTPAY_URL")
ZP_REDIRECT_FRONTEND_URL = os.environ.get("ZP_REDIRECT_FRONTEND_URL")
ZP_PAY_VERIFY_URL = os.environ.get("ZP_PAY_VERIFY_URL")

# ADMIN USER
ADMIN_USERNAME = os.environ.get("ADMIN_USERNAME")
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD")
ADMIN_FIRST_NAME = os.environ.get("ADMIN_FIRST_NAME")
ADMIN_LAST_NAME = os.environ.get("ADMIN_LAST_NAME", "!")
