# Generated by Django 5.0.1 on 2024-09-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RunSQL(
        #     sql="ALTER TABLE auth_user ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);",
        #     reverse_sql=migrations.RunSQL.noop,
        # ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.IntegerField(
                        choices=[
                            (0, "سایر"),
                            (1, "تابلوخوانی"),
                            (2, "قراردادهای اختیار معامله (آپشن\u200cها)"),
                            (3, "بورس کالای داخلی"),
                            (4, "بازارهای جهانی"),
                            (5, "مقایسه سهام"),
                        ],
                        default=0,
                        verbose_name="بخش مربوطه",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("text", models.TextField(blank=True, null=True, verbose_name="متن")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "در حال بررسی"), (1, "بررسی شده")],
                        default=0,
                        verbose_name="وضعیت",
                    ),
                ),
                ("file", models.CharField(max_length=255, verbose_name="فایل ضمیمه")),
                (
                    "receiver_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر گیرنده",
                    ),
                ),
                (
                    "sender_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر فرستنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تیکت\u200c",
                "verbose_name_plural": "۰۱) تیکت\u200cها",
            },
        ),
        migrations.CreateModel(
            name="TicketResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(blank=True, null=True, verbose_name="متن")),
                ("file", models.CharField(max_length=255, verbose_name="فایل ضمیمه")),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="support.ticket",
                        verbose_name="تیکت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ تیکت",
                "verbose_name_plural": "۰۲) پاسخ\u200cهای تیکت\u200cها",
            },
        ),
    ]
