# Generated by Django 5.0.1 on 2024-09-10 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='فایل ضمیمه'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='receiver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر گیرنده'),
        ),
        migrations.AlterField(
            model_name='ticketresponse',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='فایل ضمیمه'),
        ),
    ]
