# Generated by Django 5.0.1 on 2024-09-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_file_alter_ticket_receiver_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'بررسی نشده'), (1, 'در حال بررسی'), (2, 'پاسخ داده شده'), (3, 'بسته شده')], default=0, verbose_name='وضعیت'),
        ),
    ]
