# Generated by Django 5.0.1 on 2024-09-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'open'), (1, 'pending'), (2, 'answered'), (3, 'closed')], default=0, verbose_name='وضعیت'),
        ),
    ]
