# Generated by Django 5.0.1 on 2024-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unit',
            field=models.IntegerField(choices=[(0, 'سایر'), (1, 'مالی'), (2, 'فنی')], default=0, verbose_name='واحد مربوطه'),
        ),
    ]
