# Generated by Django 5.0.1 on 2024-09-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_ticket_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='feature',
            field=models.IntegerField(choices=[(1, 'تابلوخوانی'), (2, 'قراردادهای اختیار معامله (آپشن\u200cها)'), (3, 'بورس کالای داخلی'), (4, 'بازارهای جهانی'), (5, 'مقایسه سهام'), (0, 'سایر')], default=0, verbose_name='بخش مربوطه'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='unit',
            field=models.IntegerField(choices=[(1, 'مالی'), (2, 'فنی'), (0, 'سایر')], default=0, verbose_name='واحد مربوطه'),
        ),
    ]
