# Generated by Django 5.0.1 on 2024-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_ticket_feature_alter_ticket_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unit',
            field=models.IntegerField(choices=[(2, 'فنی'), (1, 'مالی'), (0, 'سایر')], default=0, verbose_name='واحد مربوطه'),
        ),
    ]
