# Generated by Django 5.0.1 on 2024-08-10 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("domestic_market", "0033_alter_domesticrelation_options"),
        ("global_market", "0008_alter_globalrelation_stock_instrument"),
        # ('option_market', '0004_strategy_strategy_unique_id'),
        # ('stock_market', '0043_stockinstrument_stock_instrument_unique_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockFavoriteROIGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="نام")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_roi_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock: گروه سهم\u200cهای مورد علاقه",
                "verbose_name_plural": "Stock: گروه\u200c سهم\u200cهای مورد علاقه",
            },
        ),
        migrations.CreateModel(
            name="DomesticFavoritePriceChartByCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_price_chart_by_category",
                        to="domestic_market.domesticcommodity",
                        verbose_name="کالا",
                    ),
                ),
                (
                    "commodity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_price_chart_by_category",
                        to="domestic_market.domesticcommoditytype",
                        verbose_name="نوع کالا",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_price_chart_by_category",
                        to="domestic_market.domesticindustry",
                        verbose_name="صنعت",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_price_chart_by_category",
                        to="domestic_market.domesticproducer",
                        verbose_name="تولید کننده",
                    ),
                ),
                (
                    "trade_commodity_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_price_chart_by_category",
                        to="domestic_market.domestictrade",
                        verbose_name="نام کالا",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_price_chart_by_category",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domestic: نمودار قیمت مورد علاقه بر اساس دسته\u200cبندی",
                "verbose_name_plural": "Domestic: نمودارهای قیمت مورد علاقه بر اساس دسته\u200cبندی",
                "unique_together": {
                    (
                        "user",
                        "industry",
                        "commodity_type",
                        "commodity",
                        "producer",
                        "trade_commodity_name",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="DomesticFavoritePriceChartByProducer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_price_chart_by_producer",
                        to="domestic_market.domesticcommodity",
                        verbose_name="کالا",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_price_chart_by_producer",
                        to="domestic_market.domesticproducer",
                        verbose_name="تولید کننده",
                    ),
                ),
                (
                    "trade_commodity_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_price_chart_by_producer",
                        to="domestic_market.domestictrade",
                        verbose_name="نام کالا",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_price_chart_by_producer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domestic: نمودار قیمت مورد علاقه بر اساس تولید کننده",
                "verbose_name_plural": "Domestic: نمودارهای قیمت مورد علاقه بر اساس تولید کننده",
                "unique_together": {
                    ("user", "producer", "commodity", "trade_commodity_name")
                },
            },
        ),
        migrations.CreateModel(
            name="DomesticFavoriteProducerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_producer_report",
                        to="domestic_market.domesticproducer",
                        verbose_name="تولید کننده",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_producer_report",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domestic: تولید کننده مورد علاقه برای گزارش",
                "verbose_name_plural": "Domestic: تولید کننده مورد علاقه برای گزارش",
                "unique_together": {("user", "producer")},
            },
        ),
        migrations.CreateModel(
            name="DomesticFavoriteRatioChartByCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commodity_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_category_commodity_1",
                        to="domestic_market.domesticcommodity",
                        verbose_name="کالا ۱",
                    ),
                ),
                (
                    "commodity_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_category_commodity_2",
                        to="domestic_market.domesticcommodity",
                        verbose_name="کالا ۲",
                    ),
                ),
                (
                    "commodity_type_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_category_commodity_type_1",
                        to="domestic_market.domesticcommoditytype",
                        verbose_name="نوع کالا ۱",
                    ),
                ),
                (
                    "commodity_type_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_category_commodity_type_2",
                        to="domestic_market.domesticcommoditytype",
                        verbose_name="نوع کالا ۲",
                    ),
                ),
                (
                    "industry_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_category_industry_1",
                        to="domestic_market.domesticindustry",
                        verbose_name="صنعت ۱",
                    ),
                ),
                (
                    "industry_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_category_industry_2",
                        to="domestic_market.domesticindustry",
                        verbose_name="صنعت ۲",
                    ),
                ),
                (
                    "producer_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_category_transit_1",
                        to="domestic_market.domesticproducer",
                        verbose_name="تولید کننده ۱",
                    ),
                ),
                (
                    "producer_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_category_transit_2",
                        to="domestic_market.domesticproducer",
                        verbose_name="تولید کننده ۲",
                    ),
                ),
                (
                    "trade_commodity_name_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_category_trade_commodity_name_1",
                        to="domestic_market.domestictrade",
                        verbose_name="۱ نام کالا",
                    ),
                ),
                (
                    "trade_commodity_name_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_category_trade_commodity_name_2",
                        to="domestic_market.domestictrade",
                        verbose_name="۲ نام کالا",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_category",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domestic: نسبت قیمت مورد علاقه بر اساس دسته\u200cبندی",
                "verbose_name_plural": "Domestic: نسبت\u200cهای قیمت مورد علاقه بر اساس دسته\u200cبندی",
                "unique_together": {
                    (
                        "user",
                        "industry_1",
                        "commodity_type_1",
                        "commodity_1",
                        "producer_1",
                        "trade_commodity_name_1",
                        "industry_2",
                        "commodity_type_2",
                        "commodity_2",
                        "producer_2",
                        "trade_commodity_name_2",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="DomesticFavoriteRatioChartByProducer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commodity_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_producer_commodity_1",
                        to="domestic_market.domesticcommodity",
                        verbose_name="کالا ۱",
                    ),
                ),
                (
                    "commodity_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_producer_commodity_2",
                        to="domestic_market.domesticcommodity",
                        verbose_name="کالا ۲",
                    ),
                ),
                (
                    "producer_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_producer_1",
                        to="domestic_market.domesticproducer",
                        verbose_name="تولید کننده ۱",
                    ),
                ),
                (
                    "producer_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_producer_2",
                        to="domestic_market.domesticproducer",
                        verbose_name="تولید کننده ۲",
                    ),
                ),
                (
                    "trade_commodity_name_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_producer_commodity_name_1",
                        to="domestic_market.domestictrade",
                        verbose_name="۱ نام کالا",
                    ),
                ),
                (
                    "trade_commodity_name_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_producer_commodity_name_2",
                        to="domestic_market.domestictrade",
                        verbose_name="۲ نام کالا",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domestic_favorite_ratio_chart_by_producer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domestic: نسبت قیمت مورد علاقه بر اساس تولید کننده",
                "verbose_name_plural": "Domestic: نسبت\u200cهای قیمت مورد علاقه بر اساس تولید کننده",
                "unique_together": {
                    (
                        "user",
                        "producer_1",
                        "commodity_1",
                        "trade_commodity_name_1",
                        "producer_2",
                        "commodity_2",
                        "trade_commodity_name_2",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="GlobalFavoritePriceChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_price_chart",
                        to="global_market.globalcommodity",
                        verbose_name="کالا",
                    ),
                ),
                (
                    "commodity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_price_chart",
                        to="global_market.globalcommoditytype",
                        verbose_name="نوع کالا",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_price_chart",
                        to="global_market.globalindustry",
                        verbose_name="صنعت",
                    ),
                ),
                (
                    "transit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_price_chart",
                        to="global_market.globaltransit",
                        verbose_name="ترانزیت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_price_chart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global: نمودار قیمت مورد علاقه",
                "verbose_name_plural": "Global: نمودارهای قیمت مورد علاقه",
                "unique_together": {
                    ("user", "industry", "commodity_type", "commodity", "transit")
                },
            },
        ),
        migrations.CreateModel(
            name="GlobalFavoriteRatioChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commodity_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_ratio_chart_commodity_1",
                        to="global_market.globalcommodity",
                        verbose_name="کالا ۱",
                    ),
                ),
                (
                    "commodity_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_ratio_chart_commodity_2",
                        to="global_market.globalcommodity",
                        verbose_name="کالا ۲",
                    ),
                ),
                (
                    "commodity_type_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_ratio_chart_commodity_type_1",
                        to="global_market.globalcommoditytype",
                        verbose_name="نوع کالا ۱",
                    ),
                ),
                (
                    "commodity_type_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_ratio_chart_commodity_type_2",
                        to="global_market.globalcommoditytype",
                        verbose_name="نوع کالا ۲",
                    ),
                ),
                (
                    "industry_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_ratio_chart_industry_1",
                        to="global_market.globalindustry",
                        verbose_name="صنعت ۱",
                    ),
                ),
                (
                    "industry_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_ratio_chart_industry_2",
                        to="global_market.globalindustry",
                        verbose_name="صنعت ۲",
                    ),
                ),
                (
                    "transit_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_ratio_chart_transit_1",
                        to="global_market.globaltransit",
                        verbose_name="ترانزیت ۱",
                    ),
                ),
                (
                    "transit_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_ratio_chart_transit_2",
                        to="global_market.globaltransit",
                        verbose_name="ترانزیت ۲",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_favorite_ratio_chart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global: نسبت قیمت مورد علاقه",
                "verbose_name_plural": "Global: نسبت\u200cهای قیمت مورد علاقه",
                "unique_together": {
                    (
                        "user",
                        "industry_1",
                        "commodity_type_1",
                        "commodity_1",
                        "transit_1",
                        "industry_2",
                        "commodity_type_2",
                        "commodity_2",
                        "transit_2",
                    )
                },
            },
        ),
        # migrations.CreateModel(
        #     name="OptionsFavoriteSymbol",
        #     fields=[
        #         (
        #             "id",
        #             models.BigAutoField(
        #                 auto_created=True,
        #                 primary_key=True,
        #                 serialize=False,
        #                 verbose_name="ID",
        #             ),
        #         ),
        #         ("created_at", models.DateTimeField(auto_now_add=True)),
        #         ("updated_at", models.DateTimeField(auto_now=True)),
        #         (
        #             "symbol",
        #             models.CharField(max_length=255, verbose_name="نماد مورد علاقه"),
        #         ),
        #         (
        #             "strategy",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 to="option_market.strategy",
        #                 verbose_name="استراتژی",
        #             ),
        #         ),
        #         (
        #             "user",
        #             models.ForeignKey(
        #                 on_delete=django.db.models.deletion.CASCADE,
        #                 related_name="options_favorite_symbols",
        #                 to=settings.AUTH_USER_MODEL,
        #                 verbose_name="کاربر",
        #             ),
        #         ),
        #     ],
        #     options={
        #         "verbose_name": "Options: نماد مورد علاقه",
        #         "verbose_name_plural": "Options: نمادهای مورد علاقه",
        #         "unique_together": {("user", "strategy", "symbol")},
        #     },
        # ),
        migrations.CreateModel(
            name="ROIGroupInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="stock_market.stockinstrument",
                        verbose_name="نماد",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="favorite.stockfavoriteroigroup",
                        verbose_name="گروه",
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "instrument")},
            },
        ),
    ]
