MAIN_MARKET_TYPE_DICT = {
    1: "بورس",
    2: "فرابورس",
}

ALL_MARKET_TYPE_DICT = {0: "بورس و فرابورس", **MAIN_MARKET_TYPE_DICT}

MAIN_PAPER_TYPE_DICT = {
    1: "سهام",
    2: "بازار پایه فرابورس",
}

ALL_PAPER_TYPE_DICT = {
    **MAIN_PAPER_TYPE_DICT,
    3: "تسهیلات مسکن",
    4: "حق تقدم",
    5: "اوراق بدهی",
    6: "اختیار معامله",
    7: "آتی",
    8: "صندوق‌های سرمایه‌گذاری",
    9: "بورس کالا",
}


MARKET_WATCH_COLUMN_RENAME = {
    "lva": "symbol",
    "lvc": "name",
    "pmd": "buy_price",
    "pmo": "sell_price",
    "qtj": "volume",
    "pdv": "last_price",
    "ztt": "trade_count",
    "qtc": "value",
    "bv": "base_volume",
    "pc": "last_price_change",
    "pcpc": "closing_price_change",
    "pmn": "min_price",
    "pmx": "max_price",
    "py": "yesterday_price",
    "pf": "first_price",
    "pcl": "closing_price",
    "vc": "vc",
    "csv": "csv",
    "insID": "ins_id",
    "pMax": "valid_max_price",
    "pMin": "valid_min_price",
    "ztd": "share_count",
    "blDs": "order_book",
    "insCode": "ins_code",
    "dEven": "dEven",
    "hEven": "last_time",
    "pClosing": "pClosing",
    "iClose": "iClose",
    "yClose": "yClose",
    "pDrCotVal": "pDrCotVal",
    "zTotTran": "zTotTran",
    "qTotTran5J": "qTotTran5J",
    "zTotCap": "zTotCap",
    "buy_CountI": "person_buy_count",
    "buy_I_Volume": "person_buy_volume",
    "sell_CountI": "person_sell_count",
    "sell_I_Volume": "person_sell_volume",
    "buy_CountN": "legal_buy_count",
    "buy_N_Volume": "legal_buy_volume",
    "sell_CountN": "legal_sell_count",
    "sell_N_Volume": "legal_sell_volume",
    "buy_DDD_Volume": "buy_DDD_Volume",
    "sell_DDD_Volume": "sell_DDD_Volume",
    "buy_CountDDD": "buy_CountDDD",
    "sell_CountDDD": "sell_CountDDD",
}

HISTORY_COLUMN_RENAME = {
    "date": "trade_date",
    "zTotTran": "trade_count",
    "qTotCap": "value",
    "qTotTran5J": "volume",
    "pClosing": "close_mean",
    "priceYesterday": "yesterday_price",
    "priceMin": "low",
    "priceMax": "high",
    "priceFirst": "open",
    "pDrCotVal": "close",
    "buy_I_Count": "individual_buy_count",
    "buy_I_Volume": "individual_buy_volume",
    "buy_I_Value": "individual_buy_value",
    "buy_N_Count": "legal_buy_count",
    "buy_N_Volume": "legal_buy_volume",
    "buy_N_Value": "legal_buy_value",
    "sell_I_Count": "individual_sell_count",
    "sell_I_Volume": "individual_sell_volume",
    "sell_I_Value": "individual_sell_value",
    "sell_N_Count": "legal_sell_count",
    "sell_N_Volume": "legal_sell_volume",
    "sell_N_Value": "legal_sell_value",
}

INDIVIDUAL_LEGAL_HISTORY_COLUMN_RENAME = {
    "buy_I_Count": "individual_buy_count",
    "buy_I_Volume": "individual_buy_volume",
    "buy_I_Value": "individual_buy_value",
    "buy_N_Count": "legal_buy_count",
    "buy_N_Volume": "legal_buy_volume",
    "buy_N_Value": "legal_buy_value",
    "sell_I_Count": "individual_sell_count",
    "sell_I_Volume": "individual_sell_volume",
    "sell_I_Value": "individual_sell_value",
    "sell_N_Count": "legal_sell_count",
    "sell_N_Volume": "legal_sell_volume",
    "sell_N_Value": "legal_sell_value",
    "date": "trade_date",
}

TSETMC_REQUEST_HEADERS = {
    "Accept": "application/json, text/plain, */*",
    "Accept-Encoding": "gzip, deflate, br, zstd",
    "Accept-Language": "en-US,en;q=0.9",
    "Connection": "keep-alive",
    "Host": "cdn.tsetmc.com",
    "Origin": "https://main.tsetmc.com",
    "Sec-Fetch-Dest": "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-site",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "Linux",
}

VOLUME_CHANGE_DICT = {
    "insCode": "ins_code",
    "lva": "symbol",
    "lvc": "name",
    "hEven": "last_update",
    "qtc": "value",
    "ztt": "trade_count",
    "qtj": "volume",
    "py": "yesterday_price",
    "pcl": "closing_price",
    "pdv": "last_price",
    "pc": "last_price_change",
    "pcpc": "closing_price_change",
}
